### PR TITLE
fixed issue with coder view minimized in Windows

### PR DESCRIPTION
**Pull request by adamkimbler**
I made a quick workaround for the issue I raised in #1472

### CODE REVIEW

**Comment by peircej** [comment]
Just the Coder one in the end?

**Comment by adamkimbler** [comment]
Yeah, I took a look through the builder code and it doesn't seem to have the same issue. The way it sizes the window is completely different.

**Comment by adamkimbler** [comment]
It should be fixed now, I added the BF

**Comment by peircej** [comment]
It's actually in the commit that I need it rather than the pull request. No worries though. Just for future :-)

**Pull request merged**
