### PR TITLE
BF: Reverts all commits from #2278 and #2279

### PR DESCRIPTION
**Pull request by dvbridges**
The original issue from Discourse appeared to be a problem with interpretting
mixed EOLs in Coder and code components. The original fix
attempted to convert EOLs to those defined in the preferences to provide
uniform EOLS. However, this did not address the problem described in
the original post.

### CODE REVIEW

**Comment by dvbridges** [comment]
Will open again soon. Currently looking at how text is read into the code component.

**Comment by peircej** [comment]
This pull request **introduces 2 alerts** and **fixes 1** when merging 9a1539a14cf3da87f47f4d57359ade3a4d5dad99 into bb841f575a87ebe78c5ac588a7288f728caa0841 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-989ea1417d5035326d515cd7333c5698822a9508)

**new alerts:**

* 2 for Except block handles &#39;BaseException&#39;

**fixed alerts:**

* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dvbridges** [comment]
The solution for formatting EOLs correctly on Save can be found here: 

https://discourse.psychopy.org/t/bug-disappearing-line-breaks-in-code-cells-in-builder/6607/16 

Will make another pull request with the fix.

**Comment by dvbridges** [comment]
Reopening in preparation for next release.

**Pull request merged**
