### PR TITLE
TESTS: Pin pytest version to <4.1

### PR DESCRIPTION
**Pull request by hoechenberger**
Temporary "fix" for GH-2189.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Once this has been merged into `master`, the open PRs should probably be rebased on `upstream/master` and force-pushed so that the test suit will run.

**Comment by peircej** [comment]
I'll try first just doing a test restart on travis. I can't remember if it tests on the post-merge result (in which case the tests will start passing again) or whether it only tests within the branch. I think it tests the post-merge result (that seems the "right" thing to do)

**Comment by hoechenberger** [comment]
> I can't remember if it tests on the post-merge result (in which case the tests will start passing again) or whether it only tests within the branch. I think it tests the post-merge result (that seems the "right" thing to do)

It tests the branch you intend to merge, it doesn't merge `master` first.

**Comment by peircej** [comment]
Maybe that's changed - the tests are passing with no further merge/push on my part. In fact they restarted themselves automatically too! :-)

**Comment by hoechenberger** [comment]
Wow, interesting! Good to know! But wonder _how_ that even worked… I mean, was there some magical merge performed, silently??

**Comment by peircej** [comment]
I image travis does:
```
clone orig_repo
merge pull_request
execute tests
```
It would be pretty annoying if the tests pass in the branch but fail once merged with other commits (which could happen if there were no merge step), so I think this is the right thing. If the merge fails due to a conflict then github doesn't call travis at all anyway

**Comment by hoechenberger** [comment]
> It would be pretty annoying if the tests pass in the branch but fail once merged with other commits (which could happen if there were no merge step), so I think this is the right thing.

I actually disagree, if I want to merge a branch, I want to get tested that branch specifically, and not have a silent merge committed.

Incidentally it turned out that restarting the tests "resolved" the issue by pure luck: conda installed an older pytest version now, probably because the dependencies of one of the packages we installed changed such that the latest pytest does not get installed anymore.

**Comment by hoechenberger** [comment]
But will invesitage this further and report back :)

**Comment by hoechenberger** [comment]
So Travis is def. not performing any kind of merge. This is all the `git` magic at work:
```
$ git clone --depth=50 https://github.com/psychopy/psychopy.git psychopy/psychopy
Cloning into 'psychopy/psychopy'...
remote: Enumerating objects: 4528, done.
remote: Counting objects: 100% (4528/4528), done.
remote: Compressing objects: 100% (2597/2597), done.
remote: Total 4528 (delta 2223), reused 3398 (delta 1871), pack-reused 0
Receiving objects: 100% (4528/4528), 14.01 MiB | 28.92 MiB/s, done.
Resolving deltas: 100% (2223/2223), done.
$ cd psychopy/psychopy
0.66s$ git fetch origin +refs/pull/2190/merge:
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 11 (delta 9), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/psychopy/psychopy
 * branch            refs/pull/2190/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
```

**Pull request merged**
