### PR TITLE
ENH-first name from keys == word

### PR DESCRIPTION
**Pull request by umarbrowser**
initial commit and start some..

### CODE REVIEW

**Comment by hoechenberger** [comment]
@umarbrowser 
No, you really shouldn't break an API like that.

Ok, so really, what is the deal with you? You don't seem to know PsychoPy, you seem do be doing random changes, so what is it you want? Do you want to participate in the GSoC and are trying to get in touch with an arbitrary Free Software project, hoping to get accepted? Please clearly state what you want, then we may be able to help you. What you're currently doing seems erratic, at least...

**Comment by umarbrowser** [comment]
ok i just want to you to show me step by step for fixing bugs and adding
features and i am using windows but now i want to migrate to fedora so
please needs your help

**Comment by hoechenberger** [comment]
This doesn't quite explain why you came up with this idea in the first place. What is the intention? You don't even seem to have been using PsychoPy before?

**Comment by umarbrowser** [comment]
i am  using coder only on my windows because the gui not working for me
that why i want to contribute

**Comment by hoechenberger** [comment]
Ok, great, but what was the deal with this PR then?
https://github.com/psychopy/psychopy/pull/1376

Also -- don't mean to sound rude or anything, but -- proposing changes on the GUI when you cannot even test them because it doesn't work on your computer does not seem to be the best dev practice in terms of QA :)

I also suspect you local copy of the repository is out off date, you always should pull in the latest master before any attempts to work on the code.

**Comment by umarbrowser** [comment]
ok let me check them now

**Comment by umarbrowser** [comment]
now i just need your help on how test

**Comment by hoechenberger** [comment]
I'm going assume you obviously _cannot_ test it because the GUI does not work? Or do you get to display those dialog boxes?

And _still_ I'm confused about your motivation here. You say the GUI is not working, then start proposing seemingly arbitrary changes (or maybe I just cannot follow). The chances of fixing the bug(s) that break the GUI for you are quite low with this approach...

**Comment by hoechenberger** [comment]
I mean, seriously, this INCF GSoC idea about a [BCI in PsychoPy](https://www.incf.org/collaborate/tool-development/google-summer-of-code/gsoc-2017-project-ideas) pops up and suddenly you're here... Were you accepted an need help getting started?

**Comment by umarbrowser** [comment]
No i have not been selected i just want to start contribute

**Comment by peircej** [comment]
@umarbrowser I'm afraid we don't have time to be helping teach you. I'm afraid you'll have to find another project for that. Sorry - we're just too busy to spend time checking whether your work is right and correcting you where you went wrong.

**Pull request closed without merging**
