### PR TITLE
BF: Add end routine code to save button data in JS

### PR DESCRIPTION
**Pull request by TEParsons**

### CODE REVIEW

**Comment by peircej** [comment]
Task linked: [CU-1fmebkx Button: No data saved online](https://app.clickup.com/t/1fmebkx)

**Comment by peircej** [comment]
@apitiot I'll hold off pulling this in until you've pulled in the equivalent PR at psychojs https://github.com/psychopy/psychojs/pull/483

**Comment by KarolinaCice** [comment]
Sorry, I think I have the same issue that button data is not saved in JS.
I use PsychoPy builder to build my experiment which automatically generate Python code, and also for JS.
I am new to coding and not familiar with git. So can anyone show me the code to add to make it work?

Ps. I have seen some code in commits tab which looks like a python script, but not really sure whether it has anything to do with the problem which occurs in JS and what to do with it.

**Comment by apitiot** [comment]
The PsychoJS PR has been merged :-)

**Pull request merged**
