### PR TITLE
ENH: Adds filter options to noise

### PR DESCRIPTION
**Pull request by schofiaj**
Adds the option to filter a noise sample to the noiseStim and also adds the necessary settings to the noise components. EG will allow the creation of binary noise that is then filtered with a Butterworth filter. Also adds test images but I propose to add the actual test code in a separate pull request.

### CODE REVIEW

**Comment by peircej** [comment]
This pull request **introduces 3 alerts** when merging 300ba0726a7de74b4e679026149e3eb93b6fc86b into d82304aee92c52bf92db012285464b08095c13e0 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-1fdf88c3190536d26f5dc0f3e207233b395dbdc0)

**new alerts:**

* 2 for Variable defined multiple times
* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by schofiaj** [comment]
This fails on a test that complies a builder script and compares it to the correct scripts. As I've changed the noise component in builder I guess I need to change the correct script used in the comparison. Any tips for how best to do that?

**Comment by dvbridges** [comment]
> Any tips for how best to do that?

@schofiaj , you will need to run the test that creates the new version of the correct Python scripts. First, you need to delete the current version of the correct test, so that a new one will be compiled. The correct Python scripts for the noise component are in `psychopy\psychopy\tests\data\correctScript\python`. Delete the `correctNoiseStimComponent.py` file, and then go to `psychopy\psychopy\tests\test_scripts` and run:

`pytest test_component_compile_python.py`

You will need to have the pytest library, which you can obtain using pip. When you have the new correct code, you can upload it with your new changes. You should also delete extra files that are created in the test scripts directory - the files to delete have the "new" prefix to the filename.

**Comment by schofiaj** [comment]
Ok so this is now failing for TestPygletNormNoShaders.test_radial on Python 3.7 but as far as I am aware I've not touched anything to do with radial stimuli.

**Comment by dvbridges** [comment]
> Ok so this is now failing for TestPygletNormNoShaders.test_radial on Python 3.7 but as far as I am aware I've not touched anything to do with radial stimuli.

Yes, sometimes that test fails on one of the Python versions. When this happens, you can restart the single failed test. It should pass after that.  Looks like it has passed now.

**Comment by peircej** [comment]
This pull request **introduces 3 alerts** when merging 2636b3cae063befda5009e21f7ff6b1a4b1f90e3 into 63e05e43d6fbce920a3d3fb828f411db6c6e7d92 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-ba61324c44a6bbebfce9a03cd2a4e57e11961c90)

**new alerts:**

* 2 for Variable defined multiple times
* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by schofiaj** [comment]
LGTM threw an alert which was actually a buf that I can't fix easily until I'm back in my office.

**Comment by peircej** [comment]
This pull request **introduces 2 alerts** when merging a75fabf5069b9cd6c77e8657e1f949f6cdf85755 into 63e05e43d6fbce920a3d3fb828f411db6c6e7d92 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-d79482f68e13e22a90cbc74ca0b77809dcfd6134)

**new alerts:**

* 2 for Variable defined multiple times

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request closed without merging**
