### PR TITLE
Misc: Add translation workflows

### PR DESCRIPTION
**Pull request by shun2wang**
Now we use a github action to compile all .po to .mo files once the .po was updated. demo runner at https://github.com/shun2wang/psychopy/actions/runs/7207261091

How to test this action:
1. Cherry-pick this commit to your branch
2. Change works on branch to your test branch
3. Run this action or run by manually.

TODO:
add a step to get strings from .py and update them to .pot/.po

btw: I tried use pybabel but not success and I dont konw why...

### CODE REVIEW

**Comment by peircej** [comment]
I'm not sure if it's the right approach to compile the .po files to .mo during a commit. I feel like that will lead to

lots of merge conflicts (because translators have local .mo files that the repository mo file conflicts with)
binary files that frequently change in the repository eat up space (because the entire file has to be kept in history rather than just the changes)
I agree we should be auto-compiling all files but I think it might be best at build-time instead of commit time, no?

**Comment by shun2wang** [comment]
>lots of merge conflicts (because translators have local .mo files that the repository mo file conflicts with)

Yeah, that's good a point. we can complie .mo when build a release.

Maybe we should make an action to auto update pot files and po files while source code changed. I saw that .pot/po files was out of date for a long time. and I tried use pybabel to do this but not successed, any suggestions?

All setps would be:
1. Extract origin translation strings from .py files to .POT file.
2. Update/generate locale .po files by .POT, then push to repo.
3. Make .mo files by .po files. (only release)

Should I move this PR steps to the build actions?

**Comment by peircej** [comment]
For the .pot file, I believe Jeremy Gray used to use those but I believe @hsogo wasn't bothering with them and instead just importing from source code directly to the po file periodically. I guess there's some confusion because we currently have the old pot file (which went years without any updates at all). If there is some advantage to using the pot template, e.g. so that everyone in a team is working to the same set of strings, then I'm happy to switch and start using it and then automatically update it if useful

**Comment by shun2wang** [comment]
OK I will close this for now.

**Pull request closed without merging**
