### PR TITLE
NF: Allow components to be disabled

### PR DESCRIPTION
**Pull request by hoechenberger**
During testing of an experiment, (temporarily) disabling a component can make life much easier. This PR adds a `Testing` tab to the component properties, which currently only contains a `Disable component` checkbox. If active, the component will be removed from the experiment when compiling the `psyexp` file (the original experiment / `psyexp` file will remain untouched).

Does not add the `Disable component` checkbox to `CodeComponent`s (they can still be disabled programmatically.)

screenrecording20190227at1

### CODE REVIEW

**Comment by m-macaskill** [comment]
This is great. Would actually be very nice to have this ability for entire routines too (particularly for things that differ between a development computer and the lab).

**Comment by peircej** [comment]
Yes, looks very nice. Is it good to merge?

**Comment by hoechenberger** [comment]
@m-macaskill Thanks, yes, I could try to add this in a later PR! Good idea!

@peircej I believe so… Just squashed the commits and force-pushed. Should be good to merge once the CI finishes. – Although, I have to say, I'm not happy with the current test coverage for the generated JS code (essentially zero). I should probably add at least a rudimentary test case?

**Comment by hoechenberger** [comment]
@peircej Travis isn't passing on `master`, so now my rebased branch won't pass either. Not sure it it's Travis itself or some code that got merged…

**Comment by hoechenberger** [comment]
I believe #2300 broke tests.

**Comment by peircej** [comment]
That's wierd. The tests passed on the final merge commit from that PR https://travis-ci.org/psychopy/psychopy/builds/499247480?utm_source=github_status&utm_medium=notification

What's also hard to understand is that there's no visible failure in the test suite - it just stops. My money is on some change to in Travis but hard to tell from this

**Comment by hoechenberger** [comment]
Maybe another `conda-forge` package update xD Let's see…

**Comment by hoechenberger** [comment]
So it seems to crash on `psychopy/tests/test_gui/test_DlgFromDictQt.py::TestDlgFromDictQt::test_title` (dumps core)

**Comment by hoechenberger** [comment]
Seems to be working again!

**Comment by peircej** [comment]
Yep. Wait long enough and it auto-fixes! [sigh]

**Pull request merged**
