### PR TITLE
Changes to gratingStim to add blendmode selection. Also to second order gratings, added envelope grating component to builder, added tests for second order gratings, changed grating component in builder to add blendmode selection. Documentation files to follow.

### PR DESCRIPTION
**Pull request by schofiaj**

### CODE REVIEW

**Comment by schofiaj** [comment]
Also to seocond order gratings, added evnvelope grating component to builder, added tests, chnaged grating componment in builder to add blendmode selection. Documentation files to follow.

**Comment by schofiaj** [comment]
The Travis report seems to show only one failure in the test_component section. This may be because I've added new a component and new feature to the grating component. I have provided an updated component reference file but I suspect Travis used the old one.

**Comment by schofiaj** [comment]
Just to note that in coding the component elements for builder it became clear that it relies on set functions existing for each parameter in the supporting classes. These are described elsewhere as depreciated.

**Comment by schofiaj** [comment]
This seems to be stalled. I wonder if this is due to the failed tests. I think the fix for that might be to integrate the changes one at a time and in a particular order - but I am now worried that other things will have moved on the meantime. Do you want me to start over, take account of recent updates and issue new pull requests in smaller chunks? Andrew

**Comment by peircej** [comment]
Yes, it's a mixture of the test failing (meaning I'll need to give it more than a few minutes to work out what's going on) and I've got a grant submisison dueon Mon (so don't have more than a few mins). Hopefully I'll get to it next week.

**Comment by peircej** [comment]
This has been merged in by #1381 by squashing all the commits into a single entry (hopefully I managed to preserve schofiaj as the author)

Andrew, commits should ideally have a v brief, useful name in the top (fitting on one line) and then you can give a bigger description underneath.

**Comment by schofiaj** [comment]
Thanks Jon, I took a look at the history for #1381. By the look of it I don't yet understand the components template file fully.

**Comment by peircej** [comment]
Don't worry about that. When the expected description of components changes (e.g. a new parameter) then we have to go to the tests/test_app/test_builder folder and run 
`python genComponentsTemplate.py --out`
but the times you'll need this are rare and I can do it. On this occasion I then got it wrong because I was running it on a machine that didn't have a clean unused installation!

**Comment by schofiaj** [comment]
Yes, I ran genComponentsTemplate.py and tied to incorporate the resulting template file into my pull request. Either I ran it wrong, or as with you my version wasn't clean enough or I didn't get it into github correctly.

**Pull request closed without merging**
