### PR TITLE
Create conda environment with default python

### PR DESCRIPTION
**Pull request by gbrookshire**
Installation does not work when I try to install as specified with python 3.6. When I install with python 3.7 (default) everything works correctly.

### CODE REVIEW

**Comment by peircej** [comment]
@hoechenberger @kastman does this look good to you? Are you aware of thins working on 3.7?

**Comment by hoechenberger** [comment]
I'd actually like to adjust the instructions to use the `conda-forge` package of PsychoPy and install the (few) missing deps via `pip`, as described in https://github.com/psychopy/psychopy/issues/2661#issuecomment-546685252

**Comment by hoechenberger** [comment]
@peircej I can file a PR later tonight.

**Comment by hoechenberger** [comment]
@gbrookshire As you've probably noticed, we've added a new `conda` environment file suited for end users, https://github.com/psychopy/psychopy/blob/e937f5a84b8029c554bea383906427cc250af0ca/conda/psychopy-env.yml

Could you please check if this works for you? Thanks!

**Comment by gbrookshire** [comment]
Hi @hoechenberger 
Apologies for the long delay! Unfortunately I'm getting an error when I try to install with the current conda environment file. Here's the full output. Thanks!

```
$ sudo apt install libwebkitgtk-1.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libwebkitgtk-1.0-common' for regex 'libwebkitgtk-1.0'
Note, selecting 'libwebkitgtk-1.0-0' for regex 'libwebkitgtk-1.0'
libwebkitgtk-1.0-0 is already the newest version (2.4.11-3ubuntu3).
The following packages were automatically installed and are no longer required:
  freeglut3 gdal-data gem gem-doc gem-extra gem-plugin-gmerlin gem-plugin-lqt gem-plugin-magick gem-plugin-v4l2
  ibverbs-providers ipython libaec0 libarmadillo8 libarpack2 libblosc1 libcharls1 libdap25 libdapclient6v5
  libdc1394-22 libdca0 libdrm-dev libdsdp-5.8gf libepsilon1 libfabric1 libfreexl1 libfyba0 libgavl1 libgdal20
  libgdcm2.8 libgeos-3.6.2 libgeos-c1v5 libgeotiff2 libgif7 libgl2ps1.4 libglpk40 libglvnd-core-dev libgmerlin-avdec1
  libgnutls-openssl27 libgsasl7 libhdf4-0-alt libhdf5-100 libhdf5-openmpi-100 libhwloc-plugins libhwloc5 libibverbs1
  libjs-jquery-ui libjs-sphinxdoc libjs-underscore libjsoncpp1 libkmlbase1 libkmldom1 libkmlengine1
  libkyotocabinet16v5 liblept5 libllvm7 libllvm8 libllvm8:i386 liblo7 libmailutils5 libminizip1 libmjpegutils-2.1-0
  libnetcdf-c++4 libnetcdf13 libnl-route-3-200 libntlm0 libogdi3.2 libopencv-calib3d3.2 libopencv-contrib3.2
  libopencv-core3.2 libopencv-features2d3.2 libopencv-flann3.2 libopencv-highgui3.2 libopencv-imgcodecs3.2
  libopencv-imgproc3.2 libopencv-ml3.2 libopencv-objdetect3.2 libopencv-photo3.2 libopencv-shape3.2
  libopencv-stitching3.2 libopencv-superres3.2 libopencv-video3.2 libopencv-videoio3.2 libopencv-videostab3.2
  libopencv-viz3.2 libopengl0 libopenmpi2 libportmidi0 libpostproc54 libpq5 libproj12 libpsm-infinipath1
  libpython3-dev libpython3.6-dev libqhull7 libquicktime2 librdmacm1 libsmpeg0 libsocket++1 libspatialite7
  libsuperlu5 libsz2 libtbb2 libtesseract4 liburiparser1 libvtk6.3 libwayland-bin libwayland-dev libwxbase3.0-0v5
  libwxgtk3.0-gtk3-0v5 libx11-xcb-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev
  libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxdamage-dev
  libxerces-c3.2 libxfixes-dev libxshmfence-dev libxxf86vm-dev mailutils-common mesa-common-dev odbcinst
  odbcinst1debian2 openmpi-bin openmpi-common proj-bin proj-data puredata-core puredata-dev puredata-doc
  puredata-extra puredata-utils python-antlr python-attr python-backports-shutil-get-terminal-size
  python-backports.functools-lru-cache python-certifi python-configobj python-configparser python-cvxopt
  python-cycler python-dateutil python-decorator python-et-xmlfile python-funcsigs python-future python-gevent
  python-greenlet python-ipython python-ipython-genutils python-jdcal python-joblib python-lz4 python-matplotlib
  python-matplotlib-data python-mock python-msgpack python-numexpr python-olefile python-opencv python-opengl
  python-openpyxl python-openssl python-pandas python-pandas-lib python-pathlib2 python-patsy python-pbr
  python-pexpect python-pickleshare python-pil python-pil.imagetk python-pluggy python-prompt-toolkit
  python-ptyprocess python-py python-pygame python-pyglet python-pyo python-pyparsing python-pytest python-requests
  python-scandir python-scipy python-serial python-simplegeneric python-simplejson python-statsmodels
  python-statsmodels-lib python-subprocess32 python-tables python-tables-data python-tables-lib python-traitlets
  python-tz python-urllib3 python-wcwidth python-wxgtk3.0 python-wxversion python-xlib python-xlrd python-xlwt
  python-yaml python3.6-dev ubuntu-web-launchers x11proto-damage-dev x11proto-dri2-dev x11proto-fixes-dev
  x11proto-gl-dev x11proto-xf86vidmode-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.

$ conda env create -n psychopy -f psychopy-env.yml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/home/local/ADF/brookshg/anaconda3/envs/psychopy/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/local/ADF/brookshg/Downloads/condaenv.dexr2336.requirements.txt']
Pip subprocess output:
Ignoring SoundFile: markers 'platform_system == "Windows"' don't match your environment
Collecting psychtoolbox
  Using cached psychtoolbox-3.0.16-cp36-cp36m-manylinux2010_x86_64.whl (2.0 MB)
Collecting pygame
  Using cached pygame-1.9.6-cp36-cp36m-manylinux1_x86_64.whl (11.4 MB)
Collecting pyo
  Downloading pyo-1.0.1-cp36-cp36m-manylinux1_x86_64.whl (10.8 MB)
Collecting pyparallel
  Using cached pyparallel-0.2.2-py3-none-any.whl (38 kB)
Requirement already satisfied, skipping upgrade: numpy>=1.7 in /home/local/ADF/brookshg/.local/lib/python3.6/site-packages (from psychtoolbox->-r /home/local/ADF/brookshg/Downloads/condaenv.dexr2336.requirements.txt (line 1)) (1.17.0)
Installing collected packages: psychtoolbox, pygame, pyo, pyparallel
Successfully installed psychtoolbox-3.0.16 pygame-1.9.6 pyo-1.0.1 pyparallel-0.2.2

#
# To activate this environment, use
#
#     $ conda activate psychopy
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate psychopy
$ psychopy
Traceback (most recent call last):
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/bin/psychopy", line 11, in <module>
    sys.exit(main())
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 100, in main
    start_app()
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/psychopyApp.py", line 22, in start_app
    from psychopy.app._psychopyApp import PsychoPyApp
  File "/home/local/ADF/brookshg/anaconda3/envs/psychopy/lib/python3.6/site-packages/psychopy/app/_psychopyApp.py", line 31, in <module>
    import wx
  File "/home/local/ADF/brookshg/.local/lib/python3.6/site-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/home/local/ADF/brookshg/.local/lib/python3.6/site-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /home/local/ADF/brookshg/anaconda3/envs/psychopy/bin/../lib/libgio-2.0.so.0: undefined symbol: g_spawn_async_with_fds

```

And here's the environment file, in case it's useful:
```
name: psychopy
channels:
- conda-forge
dependencies:
- python=3.6
- psychopy
- pip
- pip:
  - psychtoolbox
  - pygame
  - pyo
  - pyparallel; platform_system != "Windows"
  - SoundFile; platform_system == "Windows"
```

**Comment by gbrookshire** [comment]
I've also tried installing following the instructions for issue #2082 , but I run into the same error.

**Pull request closed without merging**
