### PR TITLE
Read from excel sheet, color changes, scoring - bugs fixed

### PR DESCRIPTION
**Pull request by anthonyhaffey**
Form can do the following now:
- Read excel files to create the survey
- Changed color scheme
- Scoring of questions and of scales

### CODE REVIEW

**Comment by peircej** [comment]
This pull request **introduces 7 alerts** when merging 4863c480d293e8ccc04277cb5e443c709f584732 into 4d9a41ada9c532bd0223495b5982520fe09a821e - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-693dfa36ba5165eb4898cd6bca84ee76d6a35764)

**new alerts:**

* 6 for Unused import
* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dvbridges** [comment]
Hi Anthony, thanks for the code. You are not going to be able to make a pull request to the master branch. You will need to create a separate branch to make the pull request. However, before you do this, the code will need refactoring. There is a alot of code to load in the excel file. This can all be achieved with a few lines of code if we use Pandas. In this way, we would call ```importItems``` from Forms init method and populate ```self.items``` with the list of dicts imported from the excel file. Nothing else will need much alteration if this is achieved. The input excel file will need to be formatted with the correct headings, e.g., 'qText', 'qWidth' etc. 

e.g.,
```
def importItems(self, items):
    """Import items from excel sheet and convert to list of dicts"""
    newItems = pd.DataFrame(items)
    newItems  = newItems.T.to_dict().values()
    return newItems
```

**Comment by peircej** [comment]
> by this point the self.name has been programatically updated to be "[survey name] | [item name]". Perhaps a clearer way to do this would be to store self.survey = [survey name], and self.name = [item name] ?

Ah, I see. Yes, don't change the Slider to handle this. In fact Slider doesn't need to know anything about belonging to a form. It can be done entirely by the Form when the data is saved:
```
for itemN, item in enumerate(self._items):

    qName = "{}.Q{}".format(self.name, itemN)  # e.g. personality.Q5 question text
    thisExp.addData(datName, item['question'].text)

    aName = "{}.A{}".format(self.name, itemN)  # e.g. personality.A5 answer value
    thisExp.addData(datName, item['response'].rating)
```

**Comment by peircej** [comment]
This pull request **introduces 6 alerts** when merging 566b9b491a45087495a15c962a35e1f04c384d1a into 2a95723d82963ed64855346d2d74c275a42d3cd5 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-9bc7cd03ef116c998b4875d0d18addd95edede25)

**new alerts:**

* 4 for Unused import
* 1 for Except block handles &#39;BaseException&#39;
* 1 for Missing call to \_\_init\_\_ during object initialization

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dvbridges** [comment]
Closing this pull request @anthonyhaffey . The Form component is now in PsychoPy 3.1.0 if you want to take a look. Your button class is already part of the master branch if you want to continue working with that as well :)

**Pull request closed without merging**
