### PR TITLE
NF: Added matrix 'concatenate' and 'invertQuat' functions.

### PR DESCRIPTION
**Pull request by mdcutone**
Added matrix concatenation function to 'mathtools' for multiplying matrix stacks, allowing you to combine matrix transformations like you would in OpenGL.

### CODE REVIEW

**Comment by mdcutone** [comment]
Added quaternion inverse function and some tests.

**Comment by peircej** [comment]
Let me know when you want this pulled in.

**Comment by mdcutone** [comment]
I'm going to test these out rendering some 3D models, if that works out I'll request a pull.

**Comment by mdcutone** [comment]
I'm going to close this to squash these commits to a single one.

**Pull request closed without merging**
