### PR TITLE
ENH: contrib tesselation code for evaluation purposes, re #936

### PR DESCRIPTION
**Pull request by jeremygray**

### CODE REVIEW

**Comment by jeremygray** [comment]
Shucks, this can sometimes work (as in the demo) but can sometimes be quite useless

screen shot 2015-11-06 at 7 00 04 am

**Comment by peircej** [comment]
Is the failure due to the order of the points ('winding  rules')?

**Comment by jeremygray** [comment]
Same result with GLU_TESS_WINDING_ODD as GLU_TESS_WINDING_NONZERO

**Comment by jeremygray** [comment]
Ok, my current approach is just wrong wrong wrong. I was fooled because it happened to work for the first example I tried, and greatly simplifies making the new class. Drat.

It is possible to use the vertices returned by tesselate.tesselate() in triplets, to build a python list of multiple separate ShapeStim, each being just a triangle. Then TessStim.draw() is just a loop to call .draw() for each triangles. This means that the right information is in there, which is good to confirm:
screen shot 2015-11-06 at 11 59 54 am

But python lists are not the way to go; much better to something similar via OpenGL in a TessStim.draw() method.

**Comment by peircej** [comment]
Look at the rendering for ElementArrayStim. It uses a list of quads, but 
the idea is the same. You provide a vertex array and tell it what those 
are. You can provide a vertex array of triangles instead. (Oh actually 
RadialStim might do that too. *Should* do that but might have been 
written before I knew about vertex arrays so might use a gl list which 
is less efficient I think).

**Pull request merged**
