### PR TITLE
BF/RF: #1578 wx version checks

### PR DESCRIPTION
**Pull request by Schubisu**
I have refactored [my previous PR](https://github.com/psychopy/psychopy/pull/1580) and dropped the `StrictVersion` version checks in favour of `pkg_resources.parse_version` comparisons.

### CODE REVIEW

**Comment by peircej** [comment]
I think this must be an issue with line 81 in `psychopy/app/builder/flow.py`
I think it must be incorrectly treating the test version (wx2.8gtk) as being wx 4, and therefore the call to the rounded rect is incorrect, but I don't know why your new use of __version__ isn't working to show that this is less than 4

**Comment by peircej** [comment]
I *wonder* whether wx in version 2.8 required us to use `version()` instead of `__version__`. I'm sure that was true at one point or we would have used `__version__` all along. But I don't know when they started allowing __version__ as well

**Comment by hoechenberger** [comment]
> I wonder whether wx in version 2.8 required us to use `version()` instead of `__version__`.

Good point, I do remember something similar, too!

**Comment by Schubisu** [comment]
Ah, okay. I will try to find out in detail and correct that. I think a version check with `parse_version` is still safer than string comparison, if done correctly ;)
But this doesn't explain why the Python 3 test fails, does it? To me, the error seems completely unrelated to the edited files.

**Comment by hoechenberger** [comment]
> But this doesn't explain why the Python 3 test fails, does it? To me, the error seems completely unrelated to the edited files.

They Py3 tests never passed so far, no need to worry about them just now.

**Comment by hoechenberger** [comment]
>> I wonder whether wx in version 2.8 required us to use version() instead of __version__.

> Good point, I do remember something similar, too!

Sorry, I was mistaken. Confused that with `pyglet`. Our current Travis setup actually does:
```
$ python -c 'import wx; print(wx.__version__)'
2.8.12.1
```
So using `__version__` should be the correct approach.

**Comment by hoechenberger** [comment]
FWIW, I've added wxPython 4 on Python 2.7 to our test environment: #1585

**Comment by peircej** [comment]
Thanks for your perseverance on this and for getting it ultimately to work. It looks like the problem was the use of "4." rather than a longer (valid) version. "4.0" is apparently OK:

```
>>> p = parse_version
>>> p('2.8.1.0')<p('4.')
False
>>> p('2.8.1.0')<p('4.0')
True
```

**Comment by Schubisu** [comment]
Yes, I realized that too late. I've choosen the `'4.'` notation because `parse_version('4.0') > parse_version('4.0.0a1') is True` and I thought it would cover all these cases. But apparently it doesn't work at all so the explicit way should be the safest.

**Pull request merged**
