### PR TITLE
TESTS, PKG: Install imageio & imageio-ffmpeg; support openpyxl 2.6

### PR DESCRIPTION
**Pull request by hoechenberger**
Closes GH-2260.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@peircej This is now good to merge.

**Comment by peircej** [comment]
This pull request **introduces 1 alert** when merging 0a6b452eec4ffcbc121b252a9e52c19badc2fa16 into 0985cd57492aa04005f183a8b71a9a3e0e2732b4 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-672e14ab49e85bc6d6eeba3c8e86282e9ffa06a2)

**new alerts:**

* 1 for Module is imported with &#39;import&#39; and &#39;import from&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
Thanks so much Richard. I so hate the packaging work! 😄

**Comment by hoechenberger** [comment]
Hah, I figured ;) No worries, you're welcome :)

**Comment by peircej** [comment]
Now, you're not going to like this, but I'm going to pull in a number of PRs where the tests haven't passed but spend my next hour or 2 making sure we get back to a passing state quickly. You might want to shut your eyes for a bit! ;-)

**Comment by hoechenberger** [comment]
*looks away, hiding the tears rolling down the cheeks*

**Comment by peircej** [comment]
and we're back to passing
https://travis-ci.org/peircej/psychopy/builds/491612654

**Pull request merged**
