### PR TITLE
BF/ENH:Switched httplib to httplib2 since httplib is outdated.

### PR DESCRIPTION
**Pull request by Infinite-PL**
I don't know if this will be useful but still I did it ;)
Signed-off-by: Michał Oszczak <mimioszczak@gmail.com>

### CODE REVIEW

**Comment by peircej** [comment]
The thing is that httplib is part of python whereas httplib2 needs to be installed by the user. Are you aware of any particular advantages that we need it for?

**Comment by Infinite-PL** [comment]
Maybe I'm wrong but httplib is no longer supported on python 3.

**Comment by peircej** [comment]
Ah, apparently so, so we will need to change at some point. Oh what about requests though?
http://docs.python-requests.org/en/master/
That's already being packaged in Standalone PsychoPy

**Comment by Infinite-PL** [comment]
So you're suggesting to instead of using httplib , use requests?

**Comment by peircej** [comment]
Yes, exactly. I think it does everything we need and more. I used `requests` for the pyosf lib which allows us to sync projects with the web from the psychopy app. It's already listed as a dependency for that reason and packaged within standalone (httplib2 is not).

There's also a note at the top of web.py saying that `mimetypes` is deprecated and we should use requests lib for that too. I don't know about that aspect.

**Pull request merged**
