### PR TITLE
 PKG, ENH, RF: Add versioneer

### PR DESCRIPTION
**Pull request by hoechenberger**
As proposed in GH-1571, I've finally found the time to add [`versioneer`](https://github.com/warner/python-versioneer).

No more out-of-sync release versions & tags!

```
$ python -c "import psychopy; print(psychopy.__version__)"
3.0.0b6+78.g13d282c3
$ git tag 3.0.0                                           
$ python -c "import psychopy; print(psychopy.__version__)"
3.0.0
```
Uncommitted changes:
```
$ touch foo; git add foo                                  
$ python -c "import psychopy; print(psychopy.__version__)"
3.0.0+0.g13d282c3.dirty
```
Committed changes:
```
$ git commit -m 'Test'
[test 0e6384a8] Test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 foo
$ python -c "import psychopy; print(psychopy.__version__)"
3.0.0+1.g0e6384a8
```

This PR also moves most of the metadata previously found in `setup.py` to `setup.cfg`. This cleans things up, avoids duplications, and was necessary to get rid of the need to `exec()` `__init__.py`, which was making things difficult.

**Currently, Travis doesn't finish successfully, although `setup.py` can build the package, and the tests pass. Any idea what's going on and if that's even related to this PR?**

### CODE REVIEW

**Comment by peircej** [comment]
> Currently, Travis doesn't finish successfully, although the build and tests pass. Any idea what's going on and if that's even related to this PR?

I'm not clear what you mean. What makes you say it doesn't finish but does pass?

**Comment by peircej** [comment]
This pull request **introduces 1 alert** and **fixes 1** when merging 13d282c30e2d3997717f2ce024b3385eb2cc8332 into f63cfc3b082f7112d7cf86bc23fe7f848e3e21c0 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-9699719da030ec91fd229b084b51fbdb09531747)

**new alerts:**

* 1 for Suspicious unused loop iteration variable

**fixed alerts:**

* 1 for Except block handles &#39;BaseException&#39;

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by hoechenberger** [comment]
Oh never mind, apparently this was just an intermittent issue that only occurred in my "personal" branch. Travis would successfully execute `setup.py build` and `setup.py install` and then run all tests, but get stalled after that. Seems not to be the case anymore!

With that out of the way -- any comments on the proposed changes? :)

**Comment by peircej** [comment]
> With that out of the way -- any comments on the proposed changes? :)

Was taking time to digest them. I think I'm fine with it. Seems like a lot of effort/code to fix a fairly inconsequential problem, but as long as I didn't spend the effort I don't mind too much! :wink:

**Pull request merged**
