### PR TITLE
Multiple improvements to data.py tests, small bugfxies, Py2/3 compat

### PR DESCRIPTION
**Pull request by hoechenberger**
This PR:

- Fixes problems with `StairHandler` tests related to temporary file generation
- Switches `data.py` tests that generate random data to a seeded `numpy.random.RandomState` for reproducibility, and updates test output files accordingly
- Adjusts `Trialhandler{2,Ext}` tests for Py2/3 compatibility
- Fixes a small bug in the `QuestHandler`
- Raises more sensible exceptions in `data.utils.importConditions`
- Switches from an ordinary `dict` to an `OrderedDict` for the conditions generated by `importConditions` for reproducible behavior (i.e., identical behavior in both Py2 and 3)

### CODE REVIEW

**Comment by hoechenberger** [comment]
Forgot to mention in the original PR summary, but all these changes here were required to get all `data.py` tests pass reliably on my system with both Py2 and 3. I had actually intended to work on something else (but also `data.py`-related), but wanted to be sure tests work correctly before proposing any functional changes. Therefore this PR build the foundation for another one to come.

**Comment by hoechenberger** [comment]
Haha wow, that was quick... I didn't mean to rush you in any way, @peircej! Seriously :)

**Comment by peircej** [comment]
Haha, no worries. Happened to be online at that moment.
Actually, when I saw this PR I suddenly worried that we might create some clashes so I wanted to find out what happened when I merged it. I've begun a branch trying to run tests on Py3.5 as well as Py2.7. The idea is to test the dependencies install by `pip install psychopy` at the same time (and simplify the travis installation script, but that has turned out harder than I thought!

https://github.com/peircej/psychopy/tree/Py3Tests

**Comment by hoechenberger** [comment]
Nice! Any particular reason for using 3.5? I'm running 3.6 locally already :)

**Pull request merged**
