### PR TITLE
ENH: Adds auto Py to JS translation for code components

### PR DESCRIPTION
**Pull request by dvbridges**
Translates code on change of code type, translate, and when code comp
closed using "OK" button (when translate set to auto).

Also:
- Metapensiero only supports Py 3.5+
- Py2 auto-translate provides user with msg - metapensiero required
- Adds test for transpiler

### CODE REVIEW

**Comment by dvbridges** [comment]
Failing because metapensiero required

**Comment by hoechenberger** [comment]
It seems indentation is 8 spaces in `py2js_transpiler.py`, while we‘re using 4 spaces in other places. Don‘t know if that‘s intentional.

**Comment by dvbridges** [comment]
> It seems indentation is done via tabs in `py2js_transpiler.py`, while we‘re using 4 spaces in other places. Don‘t know if that‘s intentional.

Ah, thanks for pointing this out. I thought I had changed all tabs to whitespace when copying over the code. Will convert and make another pull request.

**Comment by dvbridges** [comment]
@hoechenberger , I am trying to add javascripthon as a dependency, so these tests can pass. would you mind taking a look to see what needs adding?

**Comment by hoechenberger** [comment]
> @hoechenberger , I am trying to add javascripthon as a dependency, so these tests can pass. would you mind taking a look to see what needs adding?

There is no `javascripthon` on `conda-forge` yet -- I can create one later this week. Until then, you may simply get it installed via `pip` by adding an entry to the `pip` section of the `travis/environment-*.yml` files.

**Comment by peircej** [comment]
🍾

**Comment by hoechenberger** [comment]
It seems that `metapensiero.pj` only officially supports Python 3.5 and 3.6, and the latest update to the [git repository](https://github.com/metapensiero/metapensiero.pj) was in May 2018. Not sure if the project is still alive…

**Pull request merged**
