### PR TITLE
Misc iohub BF

### PR DESCRIPTION
**Pull request by isolver**
Following demos should now run on Python 3.6
 - coder/iohub/eyetracking/simple.py tested with eyelink.
 - coder/iohub/eyetracking/gcCursor/run.py tested with eyelink.
 - coder/iohub/eyetracking/selectTracker/run.py tested with eyelink and GP3. WIll not work with Tobii or SMI until those are ported to Python3
 - coder/iohub/eyetracking/gp3_simple.py with gazepoint GP3

 - coder/iohub/launchHub.py
 - coder/iohub/keyboard.py
 - coder/iohub/mouse.py

@peircej, this also has a fix that should allow iohub to start on macOS using a socket timeout like you had done, but then switches to udp socket settings to what the iohub IPC layer needs. I have not tested this on macOS though. Can you let me know if there is an issue by trying demos/coder/iohub/launchServer.py? 
Windows and Linux seem OK.

Also added back the ioHubExperimentRuntime class.

### CODE REVIEW

**Comment by peircej** [comment]
This pull request **introduces 4 alerts** and **fixes 14** when merging 83da1d365b4c66f42719a267af3d07629d74712e into dbffa6904e8f593c53234ca042053224ec3e4f09 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-7e02f549c372b93a9d3bf50687cfe24360a55c65)

**new alerts:**

* 2 for Unused import
* 1 for Except block handles &#39;BaseException&#39;
* 1 for &#39;import \*&#39; may pollute namespace

**fixed alerts:**

* 11 for Use of the return value of a procedure
* 3 for &#39;import \*&#39; may pollute namespace

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request **introduces 5 alerts** and **fixes 18** when merging cf30e823555851aae308904572aeaca70df3c2e6 into dbffa6904e8f593c53234ca042053224ec3e4f09 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-244ed3ef8a9619fc48502e29830846789ffcfe32)

**new alerts:**

* 2 for Unused import
* 1 for Unused local variable
* 1 for Except block handles &#39;BaseException&#39;
* 1 for &#39;import \*&#39; may pollute namespace

**fixed alerts:**

* 11 for Use of the return value of a procedure
* 3 for &#39;import \*&#39; may pollute namespace
* 2 for Unused local variable
* 1 for Module is imported more than once
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by isolver** [comment]
iohub eye tracking book example now works with PsychoPy3 + Python 3.6. iohub_config.yaml must be changed to use eyelink or gazepoint eye trackers at this time: SMI is still broken.

**Comment by peircej** [comment]
This pull request **introduces 5 alerts** and **fixes 18** when merging 1d5f2611a5d88f44cfba48c3e55ff3f6a44de72e into dbffa6904e8f593c53234ca042053224ec3e4f09 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-e294740ca3103ed92b8d747d0592810887c8595a)

**new alerts:**

* 2 for Unused import
* 1 for Unused local variable
* 1 for Except block handles &#39;BaseException&#39;
* 1 for &#39;import \*&#39; may pollute namespace

**fixed alerts:**

* 11 for Use of the return value of a procedure
* 3 for &#39;import \*&#39; may pollute namespace
* 2 for Unused local variable
* 1 for Module is imported more than once
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
Great. Thanks. I'll put this in PsychoPy 3.1.0

**Comment by isolver** [comment]
When are you planning to release 3.1.0? I have not had a chance to test all the changes on python 2.7 64 bit or on any OS but Windows. Should I do that before 3.1 is released? Thanks!

**Pull request merged**
