### PR TITLE
Revert translation changes from #4424 / 9d626c0

### PR DESCRIPTION
**Pull request by DimitriPapadopoulos**
Revert template and `fa_IR`/`ja_JP` to their previous state, they should not have been changed.

### CODE REVIEW

**Comment by hsogo** [comment]
Thank you for your quick response.
I found that the error is caused by change on line 8790 of ja\_JP/MESSAGE/messages.po:
```
 #, fuzzy
 #~| msgid "Data filename"
-#~ msgid "Data file delimiter"
+#~ msgid "Data file delimeter"
 #~ msgstr "データファイル名"
```
This entry seems "translation memory" created by PoEdit and it can be safely deleted.  Removing this entry, PoEdit can update the file.

**Comment by hsogo** [comment]
I tried updating fa_IR/MESSAGE/messages.po from PoEdit.  It can be updated without any error even after applying #4424.  I don't think it should be reverted.  Shall I create a pull request of my fix on ja_JP/MESSAGE/messages.po?

**Comment by DimitriPapadopoulos** [comment]
I still think it's best to revert the previous changes, including other files `psychopy/app/locale/fa_IR/LC_MESSAGE/messages.po` and template `psychopy/localization/messages.pot`.

Then you can update `psychopy/app/locale/fa_IR/LC_MESSAGE/messages.po`. It will need to be updated anyway.

**Comment by hsogo** [comment]
I've fixed only translation memory in ja\_JP/MESSAGE/messages.po. Translation memory is a set of old unused translations that is used by PoEdit to suggest translation.  I haven't modified other changes (i.e. correcting typos) you made on ja\_JP/MESSAGE/messages.po.

**Comment by peircej** [comment]
Closing in favour of #4439

**Pull request closed without merging**
