### PR TITLE
[WIP] ENH: Improve staircase test coverage, fix QUEST

### LINKED ISSUE #1006: QUEST intensity scaling should be removed
Currently, `data.QuestHandler.__init__()` takes the optional parameter `stepType`, which is later used to transform intensity values, as in:
```python
        startVal = self._intensity2scale(startVal)
        startValSd = self._intensity2scale(startValSd)
```
where `_intensity2scale()` is defined as:
```python
    def _intensity2scale(self, intensity):
        """returns the scaled intensity level based on value of self.stepType"""
        if self.stepType=='db':
            scaled_intensity = numpy.log10(intensity) * 20.0
        elif self.stepType=='log':
            scaled_intensity = numpy.log10(intensity)
        else:
            scaled_intensity = intensity
        return scaled_intensity
```
However, this interferes with the QUEST algorithm, which is implemented in `contrib.quest`, and already fully takes care of the stimulus selection. Jon also [mentioned](https://groups.google.com/d/msg/psychopy-users/5AsGnvLsPpU/wr1EPMnYJIYJ) something similar on the mailing list already.

The `stepType` argument should be removed. If a user wants to specify `startVal` and `startValSd` e.g. in terms of log intensities, they could easily do the calculation manually, i.e.,
```python
QuestHandler(np.log10(startVal), np.log10(startValSd), ...)
```
QUEST will take care of the rest.

Also, currently `stopInterval`, `minVal` and `maxVal` are not transformed, so I assume the current implementation is incorrect for all but linear `stepType`s anyway.

### LINKED ISSUE #1007: Improve test coverage for staircase procedures
Current unit test coverage for the staircase procedures in `psychopy.data` is very low or even inexistent for some staircase types.

### PR DESCRIPTION
**Pull request by hoechenberger**
**THIS IS WORK-IN-PROGRESS, PLEASE READ COMMENTS BELOW AND DO NOT MERGE YET**

QUEST intensity scaling was removed. This is a backward-incompatible change, as it removes the `stepType` keyword argument from `QuestHandler.__init__()`. This closes #1006.

This PR increases the test coverage of all except the Psi staircase methods. Particularly, it
* adds a test for log steps in the `StairHandler`,
* adds a test for the `QuestHandler`,
* introduces a base class `_BaseTestStairHandler` that implements a `simulate()` method for simplified testing,
* completely reworks `makeBasicResponseCycles()` to create simulated response cycles of arbitrary lengths.

Closes #1007 for the time being.

### CODE REVIEW

**Comment by hoechenberger** [comment]
@peircej, if you agree, I would also like to push hoechenberger/psychopy@8deaa24 to this branch.

Eventually, my goal would be adding a solution for #1005 as well, before this PR actually gets pulled. What do you think?

**Comment by hoechenberger** [comment]
I just went ahead and pushed this change (to close #1006). Will now start working on #1005. Please let me know if you don't agree with any of the changes, so I can rebase my branch to remove them.

**Comment by hoechenberger** [comment]
Seems I broke the `MultiStairhandler` tests :) Working on this.

**Comment by hoechenberger** [comment]
Need to fix #1015 first *sigh*

**Comment by peircej** [comment]
This is all great work Richard. Thanks for getting stuck in to such a thorny piece of code! :-)

**Comment by hoechenberger** [comment]
Thanks Jon, doing the best I can. Might take a little while though (1 to 2 weeks), got an urgent thing (or two :)) going on with my PhD project that requires for my attention first.

**Comment by peircej** [comment]
oops, I forgot this was still listed as a work in progress and pulled it! (I'm trying to get the code all into one state so I can run some tests locally but possibly this was on e pull too many)

**Comment by peircej** [comment]
OK I've reverted this pull so you'll need to re-issue the pull request when you're ready
cheers, Jon

**Comment by hoechenberger** [comment]
Okay, thanks for letting me know! I should probably have canceled this PR as soon as I realized more issues needed to be fixed along with this. Would have avoided the confusion. I'll create a new PR as soon as I've fixed all the problems reported. :)

**Pull request merged**
