### PR TITLE
BF: enable mouse clickable from variable online

### PR DESCRIPTION
**Pull request by RebeccaHirst**
needed to add eval() so that a value from a spreadsheet (which is read in as a string) is instead converted to an object/variable name that can be clicked.

### CODE REVIEW

**Comment by peircej** [comment]
@RebeccaHirst might this ever have the reverse problem? i.e. are there times when we _don't_ want to evaluate (e.g. if it's _not_ a variable?)

**Comment by RebeccaHirst** [comment]
@peircej the clickable field of a mouse is always an object (e.g. polygon or image) I can't think of a situation where it makes sense for a string to be clickable, it would always throw an error.

**Comment by TEParsons** [comment]
It would fail an eval if it were already an object handle though, so essentially whenever it *isn't* set via a spreadsheet. This could work though if you put it inside an `if` which checks whether it's a string before evaluating.

**Comment by TEParsons** [comment]
Okay so, something I didn't know about JS, you can `eval` a list, object handle, etc. with no problem! It just returns as is. So yes, this is fine actually :)

**Pull request merged**
