### PR TITLE
NF/RF/DOCS: Changes to gltools

### PR DESCRIPTION
**Pull request by mdcutone**
Settled on the layout of GL tools which provides a flexible means of creating FBOs and working with them. I added a context manager which helps keep track of framebuffer bindings so you don't mess up the rendering pipeline. This is going to reduce the work around adding other stereo modes and creating textures for the new 3D mesh stimuli class.  I also added a bunch of examples to the documentation. 

Texture and renderbuffer functions generate and work with descriptor datatypes (namedtuples) whose fields contain information about the buffer. Using descriptors are optional in many cases, you can extract the field of interest and discard the rest.

### CODE REVIEW

**Comment by peircej** [comment]
This pull request **introduces 1 alert** when merging 36fad793ea60ad12648e66f1ace76ce4677c7e07 into 98750f3e3fd0cafb072e77e95905eebd67981a03 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-aacf4f53d725e11f1fb20666d4a4bf44bd5e1243)

**new alerts:**

* 1 for Redundant comparison

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request **introduces 1 alert** when merging fe66a659196711eedd69925935c0e31ff04172c8 into 98750f3e3fd0cafb072e77e95905eebd67981a03 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-40258309458a0f6e83fb3702179b48df5234be33)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
I think this line is going to break Py27 again, right:
```python
def drawVertexbuffers(vertexBuffer, *args, mode=GL.GL_TRIANGLES, flush=True):
```
due to *args coming before mode and flush?

**Comment by mdcutone** [comment]
The Python 2 syntax is to put `*args` at the end? I can make another argument that takes additional buffers as a list.

**Pull request merged**
