### PR TITLE
BF: Ensure PY2/3 compatibility, remove superfluos code

### PR DESCRIPTION
**Pull request by hoechenberger**
Addresses a part of #1497.

### CODE REVIEW

**Comment by hoechenberger** [comment]
I tested pickling & unpickling using both Python 2 and 3.

**Comment by peircej** [comment]
Not sure we need to remove the code that disables the saving. The reason it's here as well as the in the save() location is that this can handle files that were created before I realised this was an issue, but probably those are long enough ago now that nobody is still opening them. 

According to the changelog this was an issue up to version 1.76.00. I guess the question is whether we support loading of data from that long ago (indeed, whether it's even possible to load data from that long ago! It won't be in Python3).

**Comment by hoechenberger** [comment]
My reasoning was that unpickling with any version of PsychoPy that was different from the exact same one used for pickling will most likely fail -- or am I mistaken here? Then again, leaving the call to `abort()` in wouldn't hurt, would it..?

**Comment by peircej** [comment]
> My reasoning was that unpickling with any version of PsychoPy that was different from the exact same one used for pickling will most likely fail -- or am I mistaken here? 

Actually yes, mistaken. ;-) The unpickling has mostly been robust to pretty much everything. The only change I know about that caused an issue was when we switched to new-style classes (subclassing `object`) and, for that, we had a period of keeping a copy of old-style classes purely for unpickling files.

I **think** Py3 is not going to be able to unpickle old files though.

**Comment by hoechenberger** [comment]
I guess you're right, closing this one.

**Pull request closed without merging**
