### PR TITLE
added to start contribute

### PR DESCRIPTION
**Pull request by umarbrowser**
i just want to contribute

### CODE REVIEW

**Comment by peircej** [comment]
I don't understand why you'd want to "contribute" by making it look like PsychoPy is associated with INCF when it isn't

**Comment by umarbrowser** [comment]
i am sorry sir please can you guide me i want to contribute on psychopy development

**Comment by hoechenberger** [comment]
@umarbrowser At the issue tracker, there's some issues tagged as `effort low`. Some of them could be a perfect starting point when thinking about contributing to PsychoPy: https://github.com/psychopy/psychopy/issues?q=is%3Aissue+is%3Aopen+label%3A%22effort+low%22

**Comment by peircej** [comment]
Please start with a fresh copy of the PsychoPy repository though before making any further changes. I won't pull in the changes that you've made so far because they will just clutter the history of the project.

Also please read the section on writing commit messages:
  http://www.psychopy.org/developers/repository.html#commit-messages

**Comment by umarbrowser** [comment]
thanks sir that will be pleasure

**Pull request closed without merging**
