### PR TITLE
Improve staircase test coverage, fix QUEST

### LINKED ISSUE #1006: QUEST intensity scaling should be removed
Currently, `data.QuestHandler.__init__()` takes the optional parameter `stepType`, which is later used to transform intensity values, as in:
```python
        startVal = self._intensity2scale(startVal)
        startValSd = self._intensity2scale(startValSd)
```
where `_intensity2scale()` is defined as:
```python
    def _intensity2scale(self, intensity):
        """returns the scaled intensity level based on value of self.stepType"""
        if self.stepType=='db':
            scaled_intensity = numpy.log10(intensity) * 20.0
        elif self.stepType=='log':
            scaled_intensity = numpy.log10(intensity)
        else:
            scaled_intensity = intensity
        return scaled_intensity
```
However, this interferes with the QUEST algorithm, which is implemented in `contrib.quest`, and already fully takes care of the stimulus selection. Jon also [mentioned](https://groups.google.com/d/msg/psychopy-users/5AsGnvLsPpU/wr1EPMnYJIYJ) something similar on the mailing list already.

The `stepType` argument should be removed. If a user wants to specify `startVal` and `startValSd` e.g. in terms of log intensities, they could easily do the calculation manually, i.e.,
```python
QuestHandler(np.log10(startVal), np.log10(startValSd), ...)
```
QUEST will take care of the rest.

Also, currently `stopInterval`, `minVal` and `maxVal` are not transformed, so I assume the current implementation is incorrect for all but linear `stepType`s anyway.

### LINKED ISSUE #1007: Improve test coverage for staircase procedures
Current unit test coverage for the staircase procedures in `psychopy.data` is very low or even inexistent for some staircase types.

### LINKED ISSUE #1015: Staircases in `MultiStairHandler` execute, but never 'finish'
It appears that, although the staircases called by `MultiStairCase` are recording all responses, they never actually transition into a `finished` state.

```python
from __future__ import print_function
from psychopy.data import MultiStairHandler
import numpy as np

np.random.seed(1000)

if __name__ == '__main__':
    nTrials = 5  # This is going to yield 5 trials per staircase.

    conditions = [
        {'label': 'stim_01', 'startVal': 0.3, 'startValSd': 0.8,
         'minVal': 0, 'maxVal': 1, 'pThreshold': 0.5, 'gamma': 0.01,
         'delta': 0.01, 'grain': 0.01, 'nTrials': nTrials},
        {'label': 'stim_02', 'startVal': 0.3, 'startValSd': 0.8,
         'minVal': 0, 'maxVal': 1, 'pThreshold': 0.5, 'gamma': 0.01,
         'delta': 0.01, 'grain': 0.01, 'nTrials': nTrials},
        {'label': 'stim_03', 'startVal': 0.3, 'startValSd': 0.8,
         'minVal': 0, 'maxVal': 1, 'pThreshold': 0.5, 'gamma': 0.01,
         'delta': 0.01, 'grain': 0.01, 'nTrials': nTrials}
    ]

    stairs = MultiStairHandler(
            stairType='quest', method='random',
            conditions=conditions, nTrials=nTrials
    )

    responses = np.tile([1, 1, 1, 0, 0, 0], 3)[:15]

    for trial, intensity in enumerate(stairs):
        stairs.addResponse(responses[trialN])

    print(stairs.finished)
    print([s.finished for s in stairs.staircases])
    print([s.thisTrialN for s in stairs.staircases])
    print([len(s.data) for s in stairs.staircases])
```
Output:
```python
False
[False, False, True]
[4, 4, 4]
[5, 5, 5]
```

Expected Output:
```python
True
[True, True, True]
[4, 4, 4]
[5, 5, 5]
```

### PR DESCRIPTION
**Pull request by hoechenberger**
QUEST intensity scaling was removed. This is a backward-incompatible change, as it removes the `stepType` keyword argument from `QuestHandler.__init__()`. This closes #1006.

This PR increases the test coverage of all except the Psi staircase methods. Particularly, it
* adds a test for log steps in the `StairHandler`,
* adds a test for the `QuestHandler`,
* introduces a base class `_BaseTestStairHandler` that implements a `simulate()` method for simplified testing,
* completely reworks `makeBasicResponseCycles()` to create simulated response cycles of arbitrary lengths,
* adds tests for `MultiStairHandler`,
* fixes a problem in `QuestHandler` that lead to the staircases not 'finishing' when run through the `MultiStairHandler`. (Closes #1015)

Closes #1007 for the time being.

*@peircej, I accidentally pulled in upstream/master at one point; I've desperately tried to rebase everything on top of master, and this PR is the result. I don't know why Github says there are merge conflicts. Could you please check and see how serious this is? If it's easy to merge by hand, I would kindly ask you to do so; if not, I'll have to look into this rebase/merge thing again, but it already cost me 2 hours :(*

### CODE REVIEW

**Comment by hoechenberger** [comment]
I forgot to remove `test_MultiStair.py` from the repository (only deleted it locally), which caused problems with the CI testing. This should be fixed now; let's see if the tests are going to pass now.

**Comment by hoechenberger** [comment]
Seems some more staircase tests are hiding in `test_TrialHandler.py`. For some reason they were not executed when I ran the test suite locally, therefore I didn't notice this earlier. Will have to look into this, please don't merge yet.

**Comment by jeremygray** [comment]
Using a graphical tool to resolve merge conflicts is nice, in my limited experience. I forget how I set it up, and have not done a merge conflict in a while. I'm happy to try to reconstruct and share the steps I took to set that up, if it's useful.

**Comment by hoechenberger** [comment]
On Wed, Nov 25, 2015 at 11:38 PM, Jeremy R. Gray
<notifications@github.com> wrote:
>
> Using a graphical tool to resolve merge conflicts is nice, in my limited experience. I forget how I set it up, and have not done a merge conflict in a while. I'm happy to try to reconstruct and share the steps I took to set that up, if it's useful.

I'd already used my IDE's built-in support for resolving merge
conflicts after pulling in upstream/master (I use PyCharm, which has
integrated Git and Github support). I just don't know where github
thinks the new merge conflicts are coming from... I could try pulling
in master again and see what happens. When I tried a couple hours ago,
only two of my commits would show up as part of the PR, although I'd
changed much more. I think this problem might have to do with the
first PR being accidentally merged and later reverted.

At any rate, I will have to fix test_TrialHandler.py first before we
can continue, anyway.

I'm super sorry for causing so much spam around here.

**Comment by jeremygray** [comment]
spam?? Not at all, communication is good! Its cool that you are engaging.

**Comment by hoechenberger** [comment]
Thanks for the encouragement :) I'll try to pull in master and rebase again tomorrow, see if this is going to improve anything :)

**Comment by hoechenberger** [comment]
I finally got it to work. After rebasing on upstream/master didn't work at all, for some reason (I've never experienced trouble of that magnitude while rebasing, ever! maybe it had something to do with the accidental merge/revert of the previous PR), essentially created a new branch from upstream/master, and then cherry-picked the commits from my other branch. And it's actually working! I opened the new PR at #1033.

**Pull request closed without merging**
