### PR TITLE
ENH: #1 refactor .travis.yml to move installation logic into scripts

### PR DESCRIPTION
**Pull request by yarikoptic**
Do not merge yet -- this is just a first step and I want to see travis reaction to changes, thus created a PR. I will buzz you when it is ready ;)

### CODE REVIEW

**Comment by peircej** [comment]
any news on this Yarik? Does the pull request need pulling?

**Comment by yarikoptic** [comment]
unfortunately I didn't have time to finalize this effort yet... if you don't mind -- could you keep it floating around?  I still hope to eventually get to it again.  IF you really want to clean up -- just close and I will open a new PR later on then

**Comment by peircej** [comment]
can I close this or merge it?

**Comment by peircej** [comment]
Just a nudge that this is still open ;-)

**Comment by yarikoptic** [comment]
Let's just close for now

**Pull request closed without merging**
