### PR TITLE
NF: Mathtools

### PR DESCRIPTION
**Pull request by mdcutone**
This commit adds a module for math functions. Particularly for performing transformations on vectors, quaternions, and vectors. This is useful for the upcoming 3D stimulus classes and for people who wish to render stimuli by computing rotation matrices. More math functions will be added over time to handle deprecated OpenGL commands.

### CODE REVIEW

**Comment by peircej** [comment]
It feels like the sort of code that should be included in the test suite pretty to check that the results being returned are as expected.

**Comment by mdcutone** [comment]
Good idea, I'll put that in too. 

I added support for deprecated OpenGL functions 'glScale', glRotate' etc. to follow modern OpenGL conventions.

**Comment by mdcutone** [comment]
Added tests for quaternion operations and rotation matrices. I know these work since I've used these exact routines for rendering 3D objects in the past, but having tests never hurt :).

BTW, all these default to float32 precision since that's what is typically used for OpenGL.

**Comment by peircej** [comment]
Great. Thanks. Yes, the idea of the test is to make sure it doesn't start failing in the future (e.g. with some change to numpy/python)

**Pull request merged**
