### PR TITLE
Text pyglet1.4

### PR DESCRIPTION
**Pull request by peircej**

### CODE REVIEW

**Comment by hoechenberger** [comment]
You're currently running these tests on `pyglet` 1.3.3, idk if. that's intentional :)

**Comment by peircej** [comment]
Not exactly but a good thing to do I suppose!

**Comment by peircej** [comment]
The changes I made are affecting both (I've moved to the new pyglet Label class even for 1.3) so we should test it there at least once! I think the issue is mostly just that the text rendering is slightly different in its aliasing - the screenshots that are non-matching look the same to the naked eye

**Comment by hoechenberger** [comment]
Tests should now run on both pyglet 1.3 and 1.4.

**Comment by hoechenberger** [comment]
🥳👌

**Pull request merged**
