### PR TITLE
BF/ENH/RF/TESTS: Various additions to Form

### PR DESCRIPTION
**Pull request by dvbridges**
A new branch for Form with all recent changes. This pull includes Anthony Haffey's button class. Other changes:

Form has been added as a Builder component with icon
Form now accepts Excel/CSV files in addition to dicts, and lists of dicts
Form returns all form data with getData()
Form checks for all items answered with formComplete()

Form refactoring
The new nested functions within the importItems method of Form class reduce duplicating code. 

TESTS:
Now test importItems and getData methods of Form class.

### CODE REVIEW

**Comment by peircej** [comment]
This pull request **introduces 2 alerts** when merging c2b17017444a427cb6adc3d900533bfb01237d1c into e97a57c6fb59f6f17a43b6f10ca9f8c379dcc59a - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-86d6673ec0cc0a6e0127e81c746604eb694f6fd8)

**new alerts:**

* 1 for Unused import
* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request **introduces 1 alert** when merging a7c11adbfdbdaec4fff7ea6460bf6fc752b749a3 into e97a57c6fb59f6f17a43b6f10ca9f8c379dcc59a - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-41e8857f7609606a17db5f5b7289145a5ee6ef27)

**new alerts:**

* 1 for Missing call to \_\_init\_\_ during object initialization

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by dvbridges** [comment]
Its passing for Python 3, not sure why it fails for Python 2.

**Comment by hoechenberger** [comment]
I think we just need to wait:

“18:40 UTC
We are working through the backlogs of webhook deliveries and Pages builds. We continue to monitor as the site recovers.”

https://status.github.com/messages

--

**Comment by dvbridges** [comment]
Thanks @hoechenberger , yes I saw the Github status messages in the end. All is well now, except for fail from exceeding the maximum log length.

**Pull request merged**
