### PR TITLE
FF: Updates to JS compiler.

### PR DESCRIPTION
**Pull request by dvbridges**
This push includes a fix that determines whether or not variables are used
as arguments in component parameters. If variables are found, they are prefixed
with 'my.'.

### CODE REVIEW

**Comment by peircej** [comment]
Ah now I understand your previous email about my.6

I added more sophisticated translation that analyses the code snippet in the way that Alain mentioned last week and only adds my you names (not variables). It's called exprrssion2js.

But it looks like I only applied that to code params, not to string params that have a $ which is went it wasn't working for you

**Comment by dvbridges** [comment]
No worries @peircej , just making the corrections and will push shortly.

**Comment by peircej** [comment]
This pull request **fixes 1 alert** when merging ee692f6be091df4d55dce00d6a62c0753c58fac2 into 8b346f61e9e1dd0027d8e83af3016f2fe1c861e5 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-5f9efba9717e5b788bcf4fa908b7505748d0dbae)

**fixed alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request **fixes 1 alert** when merging 2a8045149daf9895bc98f967708fe30d7d7f2e3c into 8b346f61e9e1dd0027d8e83af3016f2fe1c861e5 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-729a443d00e373673a547cae4a47f97bb850a4e9)

**fixed alerts:**

* 1 for Unused local variable

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Pull request merged**
