### PR TITLE
BF: Supported light and voice keys by increasing hardware button limit

### PR DESCRIPTION
**Pull request by martharobinson**
Attempts to resolve issue #1309 by increasing the number of hardcoded hardware buttons from 5 to 7.

### CODE REVIEW

**Comment by hoechenberger** [comment]
Hi @martharobinson, thanks your the contribution! I will try to look over the proposal tomorrow and get back to you.

**Comment by hoechenberger** [comment]
@martharobinson Do you have a voice key refresh detector in your lab to do some testing? I would prefer if we could introduce `voice` and `light` events, in addition to "ordinary" button presses, but I currently don't have the equipment to test such an implementation. If added these features, would you be willing to help testing?

**Comment by martharobinson** [comment]
@hoechenberger I'm afraid I don't - I contributed as part of Hacktoberfest. If I do get that equipment in the future I'd be happy to do testing, but I don't think we have plans to at the moment.

**Comment by hoechenberger** [comment]
@martharobinson Ok, thanks!

**Pull request merged**
