### PR TITLE
FF: Configuration Wizard is opened before Benchmark Wizard is opened. (issue #1203)

### PR DESCRIPTION
**Pull request by hsogo**
`BenchmarkWizard.__init__()` calls superclass's (i.e. ConfigWizard's) `__init__()`, which opens Configuration Wizard Window.

### CODE REVIEW

**Comment by peircej** [comment]
@ jeremygray could you look at this. Was there a reason at some point that this was required? Does this fix the issue of the startup wizard getting stuck open?

**Comment by hsogo** [comment]
Calling ConfigWizard's `__init__()` was added in "RF: reduce long lines in psychopy libs" (1dcc55d10b56dcf361ab2b7a2b3c8fd43e04d1fa). Then, "interactive" parameter was passed to `__init__()` in "FF: fix benchmark wizard runing under tests" (8771684e20b6cea7ef62816a4a56d754ef7957ba) to avoid opening a dialog box in the test mode.
I guess that adding ConfigWizard's `__init__()` was done as a part of refactoring. so it would not be intended to fix bugs or to add new functionality.

**Comment by peircej** [comment]
I'd still like to get @jeremygray to confirm that (he didn't get flagged in last attempt due to space after @ symbol! ;-)

**Comment by jeremygray** [comment]
I'll take a look soon.

**Comment by jeremygray** [comment]
The suggested fix will cause problems because a BenchmarkWizard object's `self.runDiagnostics` method will no longer be defined (for `diagnostics = self.runDiagnostics(win, verbose=True)`).

It will take me a little longer to track this down. At the moment, for me, the BenchmarkWizard is not opening at all, nothing happens.

**Comment by hsogo** [comment]
I am testing PsychoPy 1.84.0rc5 on Japanese Windows7, WinPython 2.7.10 and wxPython 2.8.12.1. On this environment, The BenchmarkWizard can be opened from the Builder/Coder menu with my fix...

By the way, I think that the BenchmarkWizard should not be derived from ConfigWizard.  How about making a base-wizard class and deriving the BenchmarkWizard and ConfigWizard from the base-wizard class?

**Comment by peircej** [comment]
I agree. Actually I'd rather like to revisit the startup wizard at some stage to be simpler, with fewer tests and possibly more *configuration* options, but for now we should at least get to the point that it runs!

**Comment by jeremygray** [comment]
I also agree about refactoring and the revisions.

**Comment by hsogo** [comment]
I added BaseWizard class. It passes "test_app" test on my Windows10 and Ubuntu14.04LTS.

**Pull request merged**
