### PR TITLE
RF: convert a few non_camel vars to camelCase

### PR DESCRIPTION
**Pull request by jeremygray**
Quite optional.

This was the only egregious example of multiple lower_underscore var names that I am aware of (having just looked at a lot of app/ and library code). If its worth converting things to camelCase for consistency, maybe this is a good time to do it. If not worth it, no trouble, I do not feel strongly about it.

### CODE REVIEW

**Comment by jeremygray** [comment]
Could also do the same for unit_label, mapping_func in:
tools/monitorunittools.py:88:def addUnitTypeConversion(unit_label, mapping_func):

**Comment by peircej** [comment]
Given that these are changes that don't affect users I think it's a good idea to increase the consistency

**Comment by jeremygray** [comment]
Questions:
1. `monitorunittools` seem unlikely to be used by end users -- ok to just change things like `unit_label, mapping_func` in `addUnitTypeConversion(unit_label, mapping_func)`? or make the change but also preserve backwards compatibility with a deprecation warning?
2. What about things like MonitorCenter.py, which are unusual / nonstandard because they start with a capital letter -- change to monitorCenter.py?
3. ./visual/glob_vars.py --> ./visual/globalVars.py (I have never liked glob since there is a package named glob)

**Comment by peircej** [comment]
1 `unit_label` and `mapping_func` can change I think
2 Let's not change file names. People might be running MonitorCenter or have windows shortcuts pointing to it. 
3 I don't caer about glob_vars one way or another. I forgot it existed! ;-)

**Pull request merged**
