### PR TITLE
Emotiv support

### PR DESCRIPTION
**Pull request by peircej**

### CODE REVIEW

**Comment by mdcutone** [comment]
Has anyone figured out why the builds are failing? I checked the logs but cant make sense of them to determine whether it's my code or something else causing the fault.

**Comment by peircej** [comment]
I thin that error is to do with not having a .type attribute. Trying adding that now

**Comment by peircej** [comment]
Ah @mdcutone The builds of yorur PRs appear to be failing on LGTM for some reason I don't understand unrelated to this

**Comment by peircej** [comment]
OK, this appears to be passing now.
We've also updated the icons. The new version will have a new look (including dark mode) so we wanted the icons to be sharp. Hope these are OK

image
image

**Pull request closed without merging**
