### PR TITLE
FF: integrate callbacks with iohub and fix issues with callback code

### PR DESCRIPTION
**Pull request by isolver**
FF: remove pygletbackend.onMove method, is was buggy and was shadowing BaseBackend.onMove, which is what needed to be called.
FF: fix bugs in BaseBackend onMove (can not assign elements to a tuple and onMove was calling _onResizeCallback)
FF: Adding placeholder _hw_handle to windows created using glfw backend. Should be fine for iohub multi window mouse functionality. May need to look at getting real handles in the future.
FF: Remove duplicate onResize method and double registration of the event handler in pyglet backend.

ENH: integrate onMove callback with iohub

Note: mouse_multi_window.py only works with pyglet backend at this time, as glfw does not support drawing most psychopy graphics types to multiple windows. A single glfw window (regular or full screen) could be used though.

### CODE REVIEW

**Comment by isolver** [comment]
@mdcutone, Windows created with `pyglet` backend have a  `_hw_handle` attribute that is the window handle (`int`). Can we add `_hw_handle` to Window's created with `glfw` backend? This is needed since we are using `_hw_handle` as the key for iohub window lookup operations and mouse position mapping. If you could point me in the right direction for glfw I can add the needed changes to this PR. thank you

update: for now I've updated the GlfwBackend to set `win._hw_handle = GLFWBackend._next_hw_handle`, which is a simple class counter attribute that ensures a unique  `win._hw_handle` for each GLFWBackend class instance created. This is all that is needed for the iohub multiwindow mouse enhancement. This should be changed to the actual win handle number when we determine how to do this in glfw as it is used to optionally filter keyboard and mouse events on win32 at least .

**Comment by isolver** [comment]
@mdcutone, does the `glfw` backend support drawing to multiple windows? Running the [mouse_multi_window.py](https://github.com/isolver/psychopy/blob/iohub_use_win_move_callback/psychopy/demos/coder/iohub/mouse_multi_window.py) demo (using the source from [this PR's branch](https://github.com/isolver/psychopy/tree/iohub_use_win_move_callback)) using `winType='glfw'` for both windows raises an exception. If I comment out `win2` in the demo and only draw to a single glfw window, it draws fine, without error. Both windows draw fine when `winType='pyglet'`:
```
Traceback (most recent call last):
  File "D:/DEV/my-code/psychopy/psychopy/demos/coder/iohub/mouse_multi_window.py", line 70, in <module>
    stim.draw()
  File "D:\DEV\my-code\psychopy\psychopy\visual\text.py", line 726, in draw
    self._pygletTextObj.draw()
  File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\text\layout.py", line 907, in draw
    self._batch.draw()
  File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\__init__.py", line 561, in draw
    func()
  File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\__init__.py", line 493, in <lambda>
    (lambda d, m: lambda: d.draw(m))(domain, mode))
  File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\vertexdomain.py", line 298, in draw
    buffer.bind()
  File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 403, in bind
    glBufferSubData(self.target, self._dirty_min, size,
  File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\gl\lib_wgl.py", line 107, in __call__
    return self.func(*args, **kwargs)
  File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\gl\lib.py", line 106, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid value'
```

**Comment by mdcutone** [comment]
> @mdcutone, does the `glfw` backend support drawing to multiple windows? Running the [mouse_multi_window.py](https://github.com/isolver/psychopy/blob/iohub_use_win_move_callback/psychopy/demos/coder/iohub/mouse_multi_window.py) demo (using the source from [this PR's branch](https://github.com/isolver/psychopy/tree/iohub_use_win_move_callback)) using `winType='glfw'` for both windows raises an exception. If I comment out `win2` in the demo and only draw to a single glfw window, it draws fine, without error. Both windows draw fine when `winType='pyglet'`:
> 
> ```
> Traceback (most recent call last):
>   File "D:/DEV/my-code/psychopy/psychopy/demos/coder/iohub/mouse_multi_window.py", line 70, in <module>
>     stim.draw()
>   File "D:\DEV\my-code\psychopy\psychopy\visual\text.py", line 726, in draw
>     self._pygletTextObj.draw()
>   File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\text\layout.py", line 907, in draw
>     self._batch.draw()
>   File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\__init__.py", line 561, in draw
>     func()
>   File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\__init__.py", line 493, in <lambda>
>     (lambda d, m: lambda: d.draw(m))(domain, mode))
>   File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\vertexdomain.py", line 298, in draw
>     buffer.bind()
>   File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\graphics\vertexbuffer.py", line 403, in bind
>     glBufferSubData(self.target, self._dirty_min, size,
>   File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\gl\lib_wgl.py", line 107, in __call__
>     return self.func(*args, **kwargs)
>   File "D:\Anaconda3\envs\dev38\lib\site-packages\pyglet\gl\lib.py", line 106, in errcheck
>     raise GLException(msg)
> pyglet.gl.lib.GLException: b'invalid value'
> ```

GLFW windows require an additional setup param to tell it share contexts. You need to do the following when creating successive windows:

```
glfwWin1 = Window(...) 
glfwWin2 = Window(..., backendConf={'share': glfwWin1}) 
```

**Comment by isolver** [comment]
> GLFW windows require an additional setup param to tell it share contexts. You need to do the following when creating successive windows:
> 
> glfwWin1 = Window(...) 
> glfwWin2 = Window(..., backendConf={'share': glfwWin1}) 

Added ` backendConf={'share': win}` to `win2` Window in the demo and it seems to still give the same error. 

This simple example shows the issue I'm running into, giving the same error as the demo. Help.. :)

```
from psychopy import visual, core

win = visual.Window((400, 400), pos=(0, 30), units='norm', fullscr=False, allowGUI=True, screen=0,
                    winType='glfw')
win2 = visual.Window((400, 400), pos=(500, 30), units='norm', fullscr=False, allowGUI=True, screen=0,
                    winType='glfw', backendConf={'share': win})

txt_stim = visual.TextStim(win, pos=(-0.75, 0.0), units='norm', alignText='left', anchorHoriz='left',
                                           anchorVert='center', height=.1, autoLog=False, wrapWidth=1.5,
                                           text="Hello World")
txt_stim2 = visual.TextStim(win2, pos=(-0.75, 0.0), units='norm', alignText='left', anchorHoriz='left',
                                           anchorVert='center', height=.1, autoLog=False, wrapWidth=1.5,
                                           text="Hello World")

txt_stim.draw()
txt_stim2.draw()
win.flip()

core.wait(5.0)
```

thanks again

**Review by mdcutone — APPROVED** [review]
Changes look good to me.

**Comment by mdcutone** [comment]
@isolver Approved changes to my code in the backends, but we're seeing test failing here:

```
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/psychopy/iohub/server.py", line 625, in _addDevices
    self.createNewMonitoredDevice(dev_cls_name, dev_conf)
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/psychopy/iohub/server.py", line 704, in createNewMonitoredDevice
Error:     raise ioHubError('Error during device creation ....')
psychopy.iohub.errors.ioHubError: ioHubError:
Args: ('Error during device creation ....',)
```

**Comment by isolver** [comment]
@mdcutone , I think that is because this branch was not limiting dependency pyobjc < 8.0. Merged latest dev with this branch so that should be fixed. Thank you

**Pull request merged**
