### PR TITLE
Fix a few lgtm.com alerts

### PR DESCRIPTION
**Pull request by sjvs**
This PR fixes some alerts reported by lgtm.com: https://lgtm.com/projects/g/psychopy/psychopy/alerts/

It'd be good if someone could verify whether my change to builder.py was indeed the right thing to do.

### CODE REVIEW

**Comment by peircej** [comment]
Those are fine. Thanks. FYI the reason that the bug in the builder code had not been picked up is that it's a feature I've not yet turned on! But nicer catch it beforehand! :-)

**Comment by peircej** [comment]
This pull request fixes 1 alert - [view on lgtm.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-1fa649ede6a19f4fb33197103c7c85c0836cab46)

**fixed alerts:**

* 1 for Wrong name for an argument in a call

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by peircej** [comment]
Thanks @sjvs 
Couple of things:
  - it seems to take a long time to perform the analysis - longer than our unit tests and they take up to 10 mins!
  - I doubt you'll make nay more commits to this project but, in case you do, could you use commit messages that have prefixes mentioned here (so that I know whether the changes need porting to other git branches): http://www.psychopy.org/developers/repository.html#commit-messages

thanks

**Comment by sjvs** [comment]
Thanks for the feedback @peircej. I had a quick look at what the time is spent on.

About 50 minutes is spent on setting up the right build environment (installing and building your dependencies; e.g. wxPython takes over 30 minutes). We need to replicate the build environment so we can do things like resolving types from dependencies, and analysing data flow through dependencies. If you can see anything in the [log files](https://lgtm.com/projects/g/psychopy/psychopy/logs/rev/pr-1fa649ede6a19f4fb33197103c7c85c0836cab46) that we don't need to do: please let me know!

After the build environment was set up, it took about 10 minutes to extract the relevant information from the source code for analysis. The analysis itself then took about 45 minutes, which is similar to the Travis CI build time.

Any suggestions for improvements are more than welcome!

**Comment by peircej** [comment]
Ah, OK. I think that's too long for me to use with CI. It means I either end up accepting commits where the tests haven't finished (which gives the impression to others that I'm being sloppy) or I have to wait nearly 2hrs before merging a pull request (gulp). I think I'll turn of CI and just run the test periodically when I have time to do some optimisation.

thanks

**Pull request merged**
