### PR TITLE
Window backends

### PR DESCRIPTION
**Pull request by peircej**
Refactoring the window backends to make it easier to separate the basic logic of the window from the underlying engine. This should make it easier to add further backends in future.

### CODE REVIEW

**Comment by peircej** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-47674f77002830e903f44de2fd6b76487b9e7d79)

**new alerts:**

* 1 for Unnecessary pass
* 1 for Mismatch between signature and use of an overridden method
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-94a329ca79eec5a8427192bff8292147d60e83ad)

**new alerts:**

* 1 for Unnecessary pass
* 1 for Mismatch between signature and use of an overridden method
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-f1851a0daec07275c1725cd72858e2a7a8f961ec)

**new alerts:**

* 1 for Unnecessary pass
* 1 for Mismatch between signature and use of an overridden method
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-482860eea89a41ddd82352541e571ffa04b0319a)

**new alerts:**

* 1 for Unnecessary pass
* 1 for Mismatch between signature and use of an overridden method
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by peircej** [comment]
This pull request introduces 3 alerts - [view on lgtm.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-d069a614c5463f671e2aa3ac8d29bed7351f5fc3)

**new alerts:**

* 1 for Unnecessary pass
* 1 for Mismatch between signature and use of an overridden method
* 1 for Potentially uninitialized local variable

---

*Comment posted by [lgtm.com](https://lgtm.com)*

**Comment by mdcutone** [comment]
I think *args, and **kwargs should be added to the constructor to allow further arguments from Window to get passed down to control context initialization. Thoughts?

**Comment by peircej** [comment]
yes, good point. Feel free to add as needed

**Pull request merged**
