### PR TITLE
NF: Finalised Form class

### PR DESCRIPTION
**Pull request by dvbridges**
Form class version 1 is complete (for now), complete with demo. Still needs TextBox to be added when new TextBox is finished. Icon needs work.

### CODE REVIEW

**Comment by dvbridges** [comment]
@peircej , having trouble passing tests with the new demo. Is there a process for adding demos that I need to know? Thanks

**Comment by hoechenberger** [comment]
@dvbridges @peircej I just checked: currently, not even `master` is passing Travis tests. Don't know when or how this was introduced, though… because all PRs that had been merged in the past days passed their tests.

**Comment by hoechenberger** [comment]
Update: Checked https://travis-ci.org/psychopy/psychopy/builds and it seems the tests started failing after merging https://github.com/psychopy/psychopy/commit/e95dc7af6a089b335c664814cc34ff872276b6f8, if I'm not mistaken… But I don't see how that changeset could have caused the error we're seeing now.

**Comment by hoechenberger** [comment]
I tracked it down, there's something off with the Builder Pump demo. Working on a fix.

**Comment by dvbridges** [comment]
Thanks @hoechenberger , I was going to say it looks like ```test_xsd``` is failing the ```test_Experiment```, related to the demos. I had thought the Form demo was responsible.

**Comment by hoechenberger** [comment]
Hi @dvbridges,

after #2199 has passed Travis tests and has gotten merged into `master`, you can probably pull `master` into this branch and, hopefully, everything should pass :) If not, there might still be a problem with the `Form` demo… Oh well, let's just wait and see :)

**Pull request merged**
