### PR TITLE
FF: Refactoring and fixing of Alerts

### PR DESCRIPTION
**Pull request by peircej**

### CODE REVIEW

**Comment by peircej** [comment]
> >>> import math
> >>> math.fmod(0.5, 0.01)
> 0.00999999999999999
> ```

I was thinking that was cool but did the exact same test/fail. I'm not entirely sure why this is wrong, but my handwritten version seems to work (tests included!)

**Comment by hoechenberger** [comment]
> I was thinking that was cool but did the exact same test/fail. I'm not entirely sure why this is wrong, but my handwritten version seems to work (tests included!)

Could be it does do an integer devision internally somehow still :)
trying to replicate:

```python
>>> 0.5 - 0.01 * (0.5 // 0.01)
0.010000000000000009
```

**Comment by peircej** [comment]
Damnit and now I've got to work out where the segfault is coming from :-(

**Comment by hoechenberger** [comment]
What's happened here?
`peircej:master was force-pushed and no longer has any new commits.`

**Comment by peircej** [comment]
Yes. I had to backtrack. What started as a quick-tweak on master (because I'm a bad boy) grew and grew and then I find that it's broken travis. So I've moved it to a separate branch to work out wha'ts going on
https://github.com/peircej/psychopy/tree/alerts-refactor
and reverted my master back to what it should have been ;-)

**Comment by hoechenberger** [comment]
Reminds me so much of this episode. "In and out, 20 mins adventure."
https://www.youtube.com/watch?v=xaVGvodNYW4

**Comment by peircej** [comment]
That's amazing. Never heard of Rick and Morty, but that's exactly how I feel so often!

**Pull request closed without merging**
