### PR TITLE
PKG, TESTS: Add new conda environment file for end users, update docs

### PR DESCRIPTION
**Pull request by hoechenberger**
@peircej Currently, for the latest `psychtoolbox` there's only a macOS wheel for Python 3.6 on PyPI. Would it be possible to push builds for Windows and Linux as well? (and for Py 3.7 and 3.8 too... umm... this _does_ sound like a lot of work, doesn't it?! :S)

### CODE REVIEW

**Comment by hoechenberger** [comment]
Travis is failing (on `master`, too) because there's syntactic sugar used in `visual/window.py` that's not supported by Py2

**Comment by peircej** [comment]
> 
> 
> Travis is failing (on `master`, too) because there's syntactic sugar used in `visual/window.py` that's not supported by Py2

Yes, @mdcutone added something here and I don't konw how to undo this particular sugar! (I don't know what *j is going to be used for in the shader). Matthew, woudl you be able to make it Py2 compatible again? cheers

**Comment by hoechenberger** [comment]
Rebased on `master`.

**Comment by hoechenberger** [comment]
@peircej idk why but `master` is still failing 😅

**Comment by mdcutone** [comment]
Were is it failing exactly?

**Comment by peircej** [comment]
Ah, OK. Thanks. I'll pull it in

**Comment by hoechenberger** [comment]
@kastman Forgot to put you in CC! WDYT?

**Comment by kastman** [comment]
@hoechenberger Now that it's in the wild, I'll do a better job keeping my eye out for new packaging errors! 

Env looks good, and the pip installs are clean. I'm guessing the related py38 errors are packages that just have to be updated upstream again?

**Comment by hoechenberger** [comment]
@kastman No worries :) Regarding the Py38 problems, I believe you're referring to the failed builds on `conda-forge`? It's obviously having trouble resolving the dependency tree, which I attribute to the constraints that exist in PsychoPy's dep specifications. Namely, PsychoPy doesn't support Pyglet 1.4, yet we don't havePython 3.8 builds for Pyglet 1.3.x … So I believe this is something that needs to be fixed in PsychoPy itself.

**Pull request merged**
