### PR TITLE
NF: Add QUEST+ staircase

### LINKED ISSUE #1404: QuestPlus staircase
This was first proposed on isse #1005 

I thought it would be a good idea to open an issue so we can add some resources we find online, and to discuss the proposed new class.

### PR DESCRIPTION
**Pull request by hoechenberger**
This adds the QUEST+ staircase via https://github.com/hoechenberger/questplus, and closes #1404.

Currently only supports Weibull psychometric functions and two response outcomes (`Yes/No`, `Correct/Incorrect`, etc)

Py3.6+ only.

API is open for discussion. When instantiating the staircase, a critical warning is displayed that the implementation is still fresh and might be subject to change.

Comes complete with `MultiStairHandler` and, therefore, Builder integration (via `interleaved staircases` loop option).

cc @kdesimone

@peircej I can rebase and squash commits if needed.

### CODE REVIEW

**Comment by peircej** [comment]
The decision about squash-merge or regular is mostly about whether those BF commits are really BF (need porting to existing release branch) or FF (only for >3.2.x). If they are genuine BF then I'll probably do a regular merge

**Comment by hoechenberger** [comment]
> If they are genuine BF then I'll probably do a regular merge

I assume most or all of them are FF's. I can rebase-reword.

**Comment by peircej** [comment]
>>    If they are genuine BF then I'll probably do a regular merge

> I assume most or all of them are FF's. I can rebase-reword.

Tha was my guess too. I'm happy to squash-merge thought to save you the hassle of the rebasing

**Comment by hoechenberger** [comment]
@peircej Everything should now be labeled correctly. Next step is to figure out what it is that's bugging Travis ;)

**Comment by peircej** [comment]
Your rebasing skills are clearly better/faster than mine!! :smile:

**Comment by hoechenberger** [comment]
> Your rebasing skills are clearly better/faster than mine!! 😄

I even split one of those commits into two! ;) -- I simply use PyCharm's built-in interactive rebase, makes life easy :)

**Comment by hoechenberger** [comment]
This is weird, those failing tests pass locally for me…

**Comment by hoechenberger** [comment]
Thanks Jon!

**Comment by peircej** [comment]
This pull request **introduces 1 alert** when merging 9e115d3d6d67fb1afda62175a99bc6db85d81ee8 into 14088062c579e4a15b76198ec83c22849e8188b2 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-eb37a5b05959b30e0e2233de4d8a9126111202c4)

**new alerts:**

* 1 for Mismatch between signature and use of an overridden method

---

This project has automated code review enabled, but doesn't use the <a href="https://github.com/apps/lgtm-com">LGTM GitHub App</a>. Migrate over by <a href="https://github.com/apps/lgtm-com/installations/new">installing the app</a>. Read about the <a href="https://lgtm.com/blog/announcing_github_apps_migration">benefits of migrating to GitHub Apps</a> in the blog.

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
Thank *you*! This is going to be awesome! Actually I think it's one that warrants a tweet!

**Comment by hoechenberger** [comment]
:o
Could you please label it as, well, new and experimental and such, though? ;D

--

**Pull request merged**
