### PR TITLE
NF: 10-bit display support for pyglet backend

### PR DESCRIPTION
**Pull request by mdcutone**
Adds the ability to configure the pyglet backend to use 10 bit displays. This gives the pyglet backend the same feature as the GLFW backend.

### CODE REVIEW

**Comment by peircej** [comment]
OMG. I didn't know (i.e. presumably I had forgotten) it was a relatively simple setting in the pyglet window config.
Great!

**Comment by hoechenberger** [comment]
Off-topic, but: this is weird, Travis doesn't seem to run any tests on any of @mdcutone's PRs. Therefore they all get a green tick (from LGTM). Not sure what's causing that, though. But this explains how [this issue](https://github.com/psychopy/psychopy/pull/2669#issuecomment-549733365) managed to go unnoticed.

**Comment by mdcutone** [comment]
Okay, I think that'll fix it.

**Comment by mdcutone** [comment]
Also a heads up, the new GLFW library returns things in named tuples or something for some reason.

**Comment by peircej** [comment]
> Off-topic, but: this is weird, Travis doesn't seem to run any tests on any of @mdcutone's PRs. Therefore they all get a green tick (from LGTM). Not sure what's causing that, though. But this explains how this issue managed to go unnoticed.

Yes! Just today I realised the same. Initially I though travis wasn't showing up for anyone and then today I realised that, indeed, it's just Matthew that Travis ignores! That was indeed the problem - I saw the green tick and merged :-/

**Comment by GrousexyHKCN** [comment]
hi guys, i am new to here. 
i want to show a luminance pattern by psychopy on a 10 bit display.
i wander ask if all i need to do is to set the visual.Window(…,winType=‘pyglet’, bpc=10, depthBits=10, colorSpace='rgb1'…) then the luminance(visual.GratingStim) can be changed by 1/1023 for every step?
Thanks for any response

**Pull request merged**
