### PR TITLE
FF: Stripping text field was causing error when field was None.

### PR DESCRIPTION
**Pull request by dvbridges**
This caused failure to compile script.

### CODE REVIEW

**Comment by dvbridges** [comment]
@peircej , how about setting the win size manually, if Travis is running. That way, eval does not get called.

**Comment by dvbridges** [comment]
@peircej , this has now passed the Travis testing, so good to pull in.

**Comment by peircej** [comment]
Ideally I'd like to work out why it was failing (so we know if that can happen in any real-world setting too). When it failed the error was that eval (or literal_eval) needs a string. My guess was that it was sometime given None, but maybe sometimes it's given something else. Like, maybe a numpy array or a list instead of string (ie already converted so do nothing)?

**Comment by dvbridges** [comment]
> When it failed the error was that eval (or literal_eval) needs a string. My guess was that it was sometime given None, but maybe sometimes it's given something else. Like, maybe a numpy array or a list instead of string (ie already converted so do nothing)?

Good point, I will have read about the failure and maybe some pull requests to test different scenarios.

**Comment by dvbridges** [comment]
I think it is failing because it is passed a tuple, rather than a string. So, we should test whether it is a string before trying to eval it. Ill make another fix

**Pull request merged**
