### PR TITLE
DOC: Add SliderComponent documentation

### LINKED ISSUE #3152: Builder help link for Slider component is broken
The help button in the SliderComponent in the Builder view is broken because it points to https://www.psychopy.org/builder/components/slidercomponent.html which does not exist.

### PR DESCRIPTION
**Pull request by pn2200**
Add SliderComponent documentation, fix link to documentation in SliderComponent, and fix pointer to Slider demo. Should resolve #3152.

### CODE REVIEW

**Comment by pn2200** [comment]
I did not document the `Orientation` or `Color space` fields because they don't appear to be actually wired up to do anything. Modifying `Orientation` doesn't change the `Slider` orientation or change how the `Slider` object is constructed, and similar with `Color space`.

**Comment by peircej** [comment]
ooo, @RebeccaHirst and @TEParsons have also added quite a bit of documentation recently, in PR GH-3146 which is probably going to clash with your work on this, sorry

**Comment by peircej** [comment]
I'm closing this one due to the clash with #3146 
sorry Paul! 😬

**Comment by pn2200** [comment]
That's fine. I will open a new PR to update the documentation to reflect the Slider component and to fix the other issues.

**Pull request closed without merging**
