### PR TITLE
BF: Fix exception handling

### PR DESCRIPTION
**Pull request by hoechenberger**

### CODE REVIEW

**Comment by peircej** [comment]
Is this error in the original code (i.e. it's a genuine BF, not FF)?

**Comment by hoechenberger** [comment]
This PR changes behavior that was released with 1.85.0:
https://github.com/psychopy/psychopy/compare/1.85.0...hoechenberger:exception#diff-ac47a0223c02cc101e679607adb18949L432

**Comment by hoechenberger** [comment]
We could also name this "RF", I guess... since it's not fixing a "real" bug?

**Comment by hoechenberger** [comment]
I can also rebase on 1.85.0 if that makes work easier for you!

**Comment by peircej** [comment]
No worries - just wanted to check if it was genuine BF, needing replicating across different release branches

**Pull request merged**
