### PR TITLE
BF: #1578 wx Phoenix showStartupTips

### PR DESCRIPTION
**Pull request by Schubisu**
I have scanned the psychopy code for old wx API calls just using a grep loop. I checked for all occurrences; apparently all calls have been wrapped in version query if-statements already, except the one that caused my segfault.

Nevertheless, I have replaced all occurrences of `if wx.version() > "some_version_string"` with `StrictVersion` comparisons, the used version strings have not been altered in most cases. Here's the list of occurrences that I have checked:

``` {org}
#+seq_todo: TODO | DONE NOT-APPLICABLE

* wx.AboutBox [1/1]
** DONE psychopy/psychopy/app/_psychopyApp.py:            showAbout = wx.AboutBox
   CLOSED: [2017-11-01 Wed 21:53]

* wx.AboutDialogInfo [1/1]
** DONE psychopy/psychopy/app/_psychopyApp.py:            info = wx.AboutDialogInfo()
   CLOSED: [2017-11-01 Wed 21:53]

* wx.CreateFileTipProvider [1/1]
** DONE psychopy/psychopy/app/_psychopyApp.py:            tp = wx.CreateFileTipProvider(tipFile, tipIndex)
   CLOSED: [2017-11-01 Wed 21:53]

* wx.ShowTip [1/1]
** DONE psychopy/psychopy/app/_psychopyApp.py:            showTip = wx.ShowTip(None, tp)
   CLOSED: [2017-11-01 Wed 21:53]

* wx.EmptyImage [1/1]
** DONE psychopy/psychopy/app/builder/components/__init__.py:        image = wx.EmptyImage(pil.size[0], pil.size[1])
   CLOSED: [2017-11-01 Wed 21:57]

* wx.GetDefaultPyEncoding [1/1]
** DONE psychopy/psychopy/app/coder/introspect.py:            command = command.encode(wx.GetDefaultPyEncoding())
   CLOSED: [2017-11-01 Wed 22:06]

* wx.PySimpleApp [10/10]
** DONE psychopy/psychopy/tests/test_app/test_builder/test_components.py:                tmpApp = wx.PySimpleApp()
   CLOSED: [2017-11-01 Wed 22:10]
** DONE psychopy/psychopy/tests/test_app/test_builder/genComponsTemplate.py:    tmpApp = wx.PySimpleApp()
   CLOSED: [2017-11-01 Wed 22:11]
** DONE psychopy/psychopy/tests/test_app/test_builder/genComponsTemplate.py:        tmpApp = wx.PySimpleApp()
   CLOSED: [2017-11-01 Wed 22:12]
** DONE psychopy/psychopy/tools/wizard.py:    tmpApp = wx.PySimpleApp()
   CLOSED: [2017-11-01 Wed 22:13]
** DONE psychopy/psychopy/app/preferencesDlg.py:        app = wx.PySimpleApp()
   CLOSED: [2017-11-02 Do 11:19]
** DONE psychopy/psychopy/app/dialogs.py:        app = wx.PySimpleApp()
   CLOSED: [2017-11-02 Do 11:19]
** DONE psychopy/psychopy/app/localization/__init__.py:        tmpApp = wx.PySimpleApp()
   CLOSED: [2017-11-02 Do 11:20]
** DONE psychopy/psychopy/app/builder/dialogs/dlgsConditions.py:                app = wx.PySimpleApp()
   CLOSED: [2017-11-02 Do 11:21]
** DONE psychopy/psychopy/gui/wxgui.py:            return wx.PySimpleApp()
   CLOSED: [2017-11-02 Do 11:21]
** DONE psychopy/psychopy/iohub/util/dialogs.py:                ioHubDialog.wxapp = wx.PySimpleApp()
   CLOSED: [2017-11-02 Do 11:23]

* wx.PyValidator [1/1]
** DONE psychopy/psychopy/app/builder/validators.py:    _ValidatorBase = wx.PyValidator
   CLOSED: [2017-11-02 Do 11:24]

* DrawRoundedRectangleRect [1/1]
** DONE psychopy/psychopy/app/builder/flow.py:            self.pdc.DrawRoundedRectangle = self.pdc.DrawRoundedRectangleRect
   CLOSED: [2017-11-02 Do 11:28]

* wx.lib.hyperlink [1/1]
** DONE psychopy/psychopy/app/connections.py:    import wx.lib.hyperlink as wxhl
   CLOSED: [2017-11-02 Do 11:32]

* SetToolTipString [16/16]
** NOT-APPLICABLE psychopy/psychopy/app/preferencesDlg.py:                ctrls.valueCtrl.SetToolTipString(_translate(hint))
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/preferencesDlg.py:                ctrls.valueCtrl.SetToolTipString('')
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/dialogs.py:    def SetToolTipString(self, tip):
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/dlgsCode.py:                self.componentName.SetToolTipString(param.hint)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/__init__.py:        self.valueCtrl.SetToolTipString(param.hint)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/__init__.py:        self.startTypeCtrl.SetToolTipString(self.params['startType'].hint)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/__init__.py:        self.startValCtrl.SetToolTipString(self.params['startVal'].hint)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/__init__.py:        self.startEstimCtrl.SetToolTipString(self.params['startEstim'].hint)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/__init__.py:        self.stopTypeCtrl.SetToolTipString(self.params['stopType'].hint)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/__init__.py:        self.stopValCtrl.SetToolTipString(self.params['stopVal'].hint)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/app/builder/dialogs/__init__.py:        self.durationEstimCtrl.SetToolTipString(_hnt)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/monitors/MonitorCenter.py:        self.btnNewMon.SetToolTipString(
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/monitors/MonitorCenter.py:        self.btnSaveMon.SetToolTipString(msg)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/monitors/MonitorCenter.py:        self.btnDeleteMon.SetToolTipString(msg)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/monitors/MonitorCenter.py:        self.btnCopyCalib.SetToolTipString(msg)
   CLOSED: [2017-11-02 Do 11:41]
** NOT-APPLICABLE psychopy/psychopy/monitors/MonitorCenter.py:        self.btnDeleteCalib.SetToolTipString(msg)
   CLOSED: [2017-11-02 Do 11:41]
```
I'm not sure if the commits should have been separated and tagged with **BF** for the segfault part and **RF** for the rest, and I'm not sure if these updates are desired at all, but I'm happy to update the PR if required, please advise ;)

### CODE REVIEW

**Comment by peircej** [comment]
Cool. Thanks for working that out. Yes, ideally the segfault would be a BF so that it gets ported to other branches if needed, and the other changes would be a refactor (RF)

**Comment by Schubisu** [comment]
Okay, I see that these changes rather introduce new exceptions, since apparently wx versioning hasn't always been strict. Would it be okay to use `pkg_resources.parse_version` in this case as well? It should be able to handle all these version strings correctly.
I will refactor the PR accordingly and tag the commits appropriately.

**Comment by hoechenberger** [comment]
I think both `StrictVersion(wx.__version__[:2])` and `parse_version()` should be fine.

**Comment by Schubisu** [comment]
I closed this PR in favour of [#1581](https://github.com/psychopy/psychopy/pull/1581)

**Pull request closed without merging**
