### PR TITLE
RF: Improve how subprocesses are spawned and managed

### PR DESCRIPTION
**Pull request by mdcutone**
This PR introduces the `psychopy.app.jobs.Job` class and some other changes which simplifies spawning sub-processes off the main UI process, mainly for running local scripts. Right now, the `Job` class has been applied to running local Python scripts from Runner. 

This is part of a larger project to improve parallelism in the UI.

### CODE REVIEW

**Review by TEParsons — CHANGES_REQUESTED** [review]
Are there changes to how paths are handled? When I try to run any of my demos, they error out before even loading the .py file because one folder in the path is called "My Drive" so it misinterprets the path as "E://My"

**Comment by mdcutone** [comment]
> 
> 
> Are there changes to how paths are handled? When I try to run any of my demos, they error out before even loading the .py file because one folder in the path is called "My Drive" so it misinterprets the path as "E://My"

I'll see if I can figure this out. Don't recall changing any path stuff, but I might have messed up handling them somehow.

**Comment by peircej** [comment]
One path issue is that I was setting popen explicitly to use the file folder as the current working directory for running the study which doesn't seem to be done in this system?

**Comment by mdcutone** [comment]
> One path issue is that I was setting popen explicitly to use the file folder as the current working directory for running the study which doesn't seem to be done in this system?

Might be due to spaces in the paths like Todd suggested. I just put quotes around those before passing it to the `Job` constructor.

**Review by TEParsons — APPROVED** [review]
Spaces in filename bug seems to be fixed, no longer erroring when I try to run stuff, now seems to be working fine!

**Comment by peircej** [comment]
This looks good. Do you think a test to the test suite that launches a process by this? So we could at least flush the code in the test suite and catch typos? Ideally we'd create a test process that generates expected outputs and check we receive them but just making sure a process can be launched and completed seems useful

**Review by peircej — COMMENTED** [review]
This looks good. Do you think a test to the test suite that launches a process by this? So we could at least flush the code in the test suite and catch typos? Ideally we'd create a test process that generates expected outputs and check we receive them but just making sure a process can be launched and completed seems useful

**Pull request merged**
