### PR TITLE
BF: Switch to AddTool for Builder Frame as AddSimpleTool deprecated...

### PR DESCRIPTION
**Pull request by dvbridges**
However, having found msg in _psychopyApp.py that AddTool breaks in version 3.0.2, holding off on further work. If it is time to switch, will replace remaining AddSimpleTool calls.

### CODE REVIEW

**Comment by dvbridges** [comment]
@peircej do you know if AddTool still breaks in version 3.0.2?

**Comment by dvbridges** [comment]
@peircej , this still breaks with wx3, so I am closing this pull request.

**Comment by peircej** [comment]
Yes, I added something at the start of psychopyApp to turn off the warning:

https://github.com/psychopy/psychopy/blob/b6f17b791170e33d839df1a4f21b0bd91b96406b/psychopy/app/_psychopyApp.py#L33

I think we need to wait until people aren't using Py2 anymore (when they switch to Py3 they'll switch to wx4)

**Comment by peircej** [comment]
I mean, when we stop supporting Py2 with new releases. They can still use older versions, with Py2 and the change won't be a problem.

**Pull request closed without merging**
