### PR TITLE
ENH: Allow specification of QuestPlus prior probabilities

### PR DESCRIPTION
**Pull request by hoechenberger**
This also pins Travis's Python 3.7 to 3.7.3, as 3.7.6 (latest 3.7 release on conda-forge) exposes a bug in pyglet's xlib support: https://github.com/pyglet/pyglet/issues/112

### CODE REVIEW

**Comment by peircej** [comment]
Oh, hey, is this ready to go?

**Comment by hoechenberger** [comment]
@peircej Yep!

**Comment by hoechenberger** [comment]
@peircej maybe i should rebase first though?

**Comment by hoechenberger** [comment]
@peircej Good to merge.

**Pull request merged**
