### PR TITLE
RF: replace bare except statements

### PR DESCRIPTION
**Pull request by jeremygray**
Replace with `except Exception:` instead. This is a functional change: a bare except will catch SystemExit. The new way allows using sys.exit() to quit a script, e.g., in conjunction with atexit module; see #1083
Some (many?) of the instances of Exception could be replaced with a more specific exception. ImportError are easy to infer but others are less so.

### CODE REVIEW

**Comment by peircej** [comment]
Would you mind doing a pull from upstream and fixing, the merge conflict, and resubmitting the pull request?

**Comment by jeremygray** [comment]
Done! And I'm done for the rest of the week too.

**Comment by jeremygray** [comment]
The merge conflict is fixed, reopening the PR.

**Comment by peircej** [comment]
Should I pull this in? 
Specifying which specific error, as @toddrjen suggests, is fine but we need to be pretty certain that the except isn't catching multiple different errors with a single resolution. I've certainly been lazy on checking what range of errors might occur, but that's also more likely to catch the problem before it leaves the area of interest?

**Comment by jeremygray** [comment]
Yes, please pull it in in its current state. This is an improvement over bare excepts, and does so quite safely. Doing the additional work of more specific exceptions is indeed worth doing in those cases where it is clear what the failures will be, but will take longer.

**Comment by peircej** [comment]
My thoughts exactly. Done :-)

**Pull request merged**
