### PR TITLE
TESTS: Add Anaconda builds & tests for Python 2.7 and 3.6

### PR DESCRIPTION
**Pull request by hoechenberger**
I expanded our testing (Travis) setup to use Anaconda for setting up Python 2.7 and 3.6 environments, and tuned some tiny bits and pieces here and there.

This PR:
- Now also tries to build & install PsychoPy, instead of simply running the tests on the downloaded source tree
- Adds Anaconda testing environments for Python 2.7 and 3.6, while preserving our previous test setup. That is, we now have a testing matrix that includes non-Anaconda 2.7, Anaconda 2.7, and Anaconda 3.6
- Fixes bugs in `iohub` and the `MovieStim2` demo

I don't know if all dependencies for properly testing on Python 3 are actually installed, because obviously `pytest` fails quite early. We'll now just have try and fix the Python3 show stoppers one by one, and add additional required packages whenever needed.

As a next step, I would like to add `macOS` to the test matrix, and set up AppVeyor after that.

Relates to #1571.

### CODE REVIEW

**Comment by peircej** [comment]
Looks amazing Richard (and I know how much effort this takes)! Cool that you got it to test on the built-in *and* on the conda method. What are your thoughts about keeping them both? It seems it won't substantially change test duration because they run parallel.

My guess is that it will take a little while to get the py3.6 tests passing. Do you happen to know if we can change the Travis button so that it reflects a "passing" state if the 2.7 installations pass?

Anyway, great work! :-) Do you want me to hold off merging for now? I'm happy to merge, given that the 2.7 tests pass (on two separated sets of dependent libs!)

**Comment by hoechenberger** [comment]
> Looks amazing Richard (and I know how much effort this takes)! Cool that you got it to test on the built-in and on the conda method. What are your thoughts about keeping them both? It seems it won't substantially change test duration because they run parallel.

Thanks Jon :) I wanted to keep them both for the time being -- like you said, parallel builds don't extend testing time, so it doesn't hurt!

> > My guess is that it will take a little while to get the py3.6 tests passing. Do you happen to know if we can change the Travis button so that it reflects a "passing" state if the 2.7 installations pass?

I've added an `allow_failures` section to `.travis.yml`, which does just that!

> Anyway, great work! :-) Do you want me to hold off merging for now? I'm happy to merge, given that the 2.7 tests pass (on two separated sets of dependent libs!)

I'm not sure about the coverage information that is reported here; I don't know if it's the combined coverage of all tests (including the failing one)?! Maybe we should invoke `coverage` only for one of the builds?

**Comment by hoechenberger** [comment]
Mhh ok, according to `https://coveralls.io/builds/13843338` only the successful (Python 2.7) builds are considered by coveralls. Makes me wonder why the coverage is so massively decreased?! Did I break anything?

**Comment by peircej** [comment]
Don't know. Mysterious :-/

**Comment by peircej** [comment]
I think excluding iohub is probably reasonable. As you say, most of the hardware can't be accessed anyway. Was it being excluded before? Is that why the coverage was where it is?

**Comment by hoechenberger** [comment]
@peircej Should be good to merge now!

**Pull request merged**
