### PR TITLE
NF and FFs: Scoring, reading csv in Forms

### PR DESCRIPTION
**Pull request by anthonyhaffey**
Form class should now be able to:
- read csv
- calculate score (for radio trials at least)

No attempt to make anything other than radio and instruct work.

### CODE REVIEW

**Comment by peircej** [comment]
Ant, could you follow the guidelines at http://www.psychopy.org/developers/repository.html#commit-messages about using prefixes on your commit messages please? Thanks. In particular fixes to code that you've just created should be labelled as FF versus fixes to released code (which you're probably not doing much of) are BF

**Comment by anthonyhaffey** [comment]
Hi Jon, sorry for overlooking the guidelines, I’ll make sure to do so

**Comment by peircej** [comment]
This pull request **fixes 5 alerts** when merging 32d631cf17dd204c241ef58a2c47005d0ea93b35 into e5821bfd87f52ce4e51ca9197f2b7f5d5d363788 - [view on LGTM.com](https://lgtm.com/projects/g/psychopy/psychopy/rev/pr-34cfd8eb2c9f77395db85d67799188193c777ad4)

**fixed alerts:**

* 3 for Unused local variable
* 1 for Unused import
* 1 for Missing call to \_\_init\_\_ during object initialization

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by peircej** [comment]
Some further points...

The demo really needs to be smaller and focus just on the things that are needed to use a form. Aim for 30-50 lines. Users need to see this is easy and understandable. At the moment, with over 100 lines of demo, it looks like there's an awful lot to learn in order to present a simple form. People won't touch it if it looks complicated. See demos for gratings, images etc to get a feel for how a simple demo should look. 

This is a big piece of work that should really be going on in a separate branch, not the master. Sorry, the commit from @dvbridges accidentally went in to master instead of the `form` branch that I had created, but `master` isn't the place for works in progress. This isn't ready for real use yet, right?  Or is it done do you think?

**Comment by anthonyhaffey** [comment]
Hi Jon, I think there might have been some misunderstandings (exacerbated by my mistakes in making pull requests), see my comments below in **bold**:

> Some further points...
> 
> The demo really needs to be smaller and focus just on the things that are needed to use a form. Aim for 30-50 lines. Users need to see this is easy and understandable. At the moment, with over 100 lines of demo, it looks like there's an awful lot to learn in order to present a simple form. People won't touch it if it looks complicated. See demos for gratings, images etc to get a feel for how a simple demo should look.
**Sorry, it was a mistake for me to try to put in a demo at this stage. I removed it in one of my [commits](https://github.com/psychopy/psychopy/pull/2027/commits/4863c480d293e8ccc04277cb5e443c709f584732), so it shouldn't be present in this pull request.**

> 
> This is a big piece of work that should really be going on in a separate branch, not the master. Sorry, the commit from @dvbridges accidentally went in to master instead of the `form` branch that I had created, but `master` isn't the place for works in progress. This isn't ready for real use yet, right? Or is it done do you think?
**Yes, it's a work in progress rather than ready for use - I think some confusion has arisen from my previous pull request to the master branch (sorry), but I believe this one is to the _Form_ branch? I'm still new to pull requests, so I may be misunderstanding.**

**Comment by peircej** [comment]
Oh! haha, Yes this one is to the form branch. All good. :-)
Don't worry - *having* a demo is fine (since this is in a separate development branch. I'm just alerting you to the need to keep the demo super-simple to show (only) how the form works

**Pull request merged**
