### PR TITLE
TESTS: Pin pip to version <19.0 and ensure packages are not updated when installing a new conda package

### PR DESCRIPTION
**Pull request by hoechenberger**
Addresses GH-2238 and ensures `conda` will not update arbitrary packages when we try to install another one.

### CODE REVIEW

**Comment by hoechenberger** [comment]
There was a change to the `qt` `conda-forge` package 3 days ago: https://github.com/conda-forge/qt-feedstock/pull/90

**Comment by peircej** [comment]
Conda and pip seem to break our tests much more often than our own code!

**Comment by hoechenberger** [comment]
Hah. These filenames actually contain commas. We should rename them.

**Comment by hoechenberger** [comment]
Related issue: https://github.com/pypa/wheel/issues/280

**Comment by hoechenberger** [comment]
Tests at least pass locally for me on macOS.

**Comment by hoechenberger** [comment]
Travis installs `gstreamer` via `apt` -- probably as a dependency of something, while the change that was made to the `qt` package in conda-forge/qt-feedstock#90 is simply an adjustment of deps -- towards `gstreamer`. I guess there's a collision of some kind now on our testing system.

**Comment by hoechenberger** [comment]
Potentially related: https://github.com/conda-forge/gstreamer-feedstock/issues/23

We could try to pin to the previous `qt` version for now, or just wait a little for a new `gstreamer` release and see if that fixes things.

**Comment by peircej** [comment]
Not sure what gstreamer is there for unless it's needed by something else like QT. I looked at it briefly as an alternative to opencv for MovieStim (I believe OpenSesame uses GStreamer) but decided against it because it was painful to install. So maybe the gstreamer install is a hangover from that

**Comment by hoechenberger** [comment]
It seems to get installed as one of the many dependencies of `libwebkitgtk-1.0-0`.

**Comment by hoechenberger** [comment]
I looked through the Travis log again. I now believe the issue is _not_ a conflict between system and conda libs (so the commit I just made is not going to fix it); rather, when installing `openpyxl` and / or `wxpython` "post-hoc" (as we do in the Python 2 environments), suddenly qt and gstreamer versions from the `defaults` channel get installed, replacing the `conda-forge` packages that were installed previously (via the environments files).

This explains why we see the problem with our Python 3 tests only – they don't do this kind of install-packages-after-initial-setup thing.

**Comment by hoechenberger** [comment]
Followup:

- `wxpython` 3 is not available from `conda-forge`, therefore installing this version will fetch it from `defaults`, including `qt` and `gstreamer` deps from this channel
- installation of `openpyxl`, for some reason, retrieves a bunch of additional packages from `defaults`, including `qt` and `gstreamer`

**Comment by hoechenberger** [comment]
Potentially relevant: https://github.com/conda/conda/issues/7261

**Comment by hoechenberger** [comment]
@peircej I rebased to clean the commit history. This should be good to merge once Travis is done testing.

**Comment by peircej** [comment]
Still amazed that any of these things are installing gstreamer! Potentially we could replace openpyxl with either xlsxwriter/xlsreader combo  (which I think pandas uses by default) or from xlwings (which also looks cool for the fact we can write python plugins from excel!)

**Comment by hoechenberger** [comment]
@peircej `qt` depends on `gstreamer` (on `conda-forge`, that is); neither `openpyxl` nor `wxpython` directly depend on the former two. Not really sure why `conda` tried to update some of the (implicit?) deps when installing `openpyxl` and `wxpython`. But this is now resolved thanks to using the `--freeze-installed` option we pass to `conda`. Before this parameter was set, we would apparently sometimes end up with a mixture of `conda-forge` and `defaults` packages, which is discouraged and probably the cause of the `qt`-related issue we saw here. To prevent this from happening in the future, I have prepared #2240, which ensures all deps are getting installed from `conda-forge` only.

**Pull request merged**
