### PR TITLE
BF: Pygelt 1.3 and 1.4 compatibility

### PR DESCRIPTION
**Pull request by mdcutone**
Fix allows psychopy to use Pyglet version 1.3 and 1.4. Not sure if I caught all the issues but the demos seem to work fine.

### CODE REVIEW

**Comment by mdcutone** [comment]
Don't pull this in until I refine it a bit.

**Comment by hoechenberger** [comment]
pyglet 1.4.2 also [added](https://github.com/pyglet/pyglet/blob/f5491971f21d32d1403c8749fe10c1c9ec9cf0bd/RELEASE_NOTES#L8) a
> `Window.get_pixel_ratio` function for calculating scaling on HiDPI displays.

wonder if that could make things easier and less error-prone for Macs?

**Comment by peircej** [comment]
I wanted to pull this in ready for a 3.2.0dev1 release, to test a range of things in a full release

**Comment by peircej** [comment]
@hoechenberger that function is helpfull in detecting that this is a system with silent upscaling, but doesn't ultimately fix the central issue of how we present these screens to users.

**Comment by mdcutone** [comment]
I'm going to look into the suggestions posted in  #2518. He seems to have better figured out what was exactly refactored on the Pyglet end. I'm trying to only version check once upon loading the backend, instead of evaluating the ``if version <1.4`` every time.

**Pull request merged**
