### PR TITLE
NF: Coder UI enhancements

### PR DESCRIPTION
**Pull request by mdcutone**
This PR removes the defunct "Source Assistant" and replaces it with a source code tree and file browser. 

The source code tree displays classes and definitions within the current document. Giving you an outline of your file which makes navigation much easier. You can click on tree items to expand them and goto their definitions in the file. I decided to go with a quick-and-dirty approach to parsing the file, instead of using the AST. This method is much faster and can do really time parsing on very large files. Right now only function and class definitions show up, in the future variables, imports and attributes will also be displayed. 

I also added an integrated file browser panel, it looks and behaves much like the one in R Studio. You can open files by clicking on them, or rename and delete them if you like. I also added a menu option that allows you to change the current working directory of Coder. This allows you to work within a project directory. You can change the CWD to a custom location, to the location of the presently opened file, or the directory being shown in the file pane. 

There are also a bunch of misc features and fixes:
* I added new fields to the status bar in coder which displays the current line number and column, and file type.
* Disabled lexer for non-code text files. No longer is there syntax highlighting when viewing a CSV or text document.
* Added Close All and Close others menu items.
* Fixed lexers not being set correctly. They all work now and they're ugly.

### CODE REVIEW

**Comment by m-macaskill** [comment]
👍 Oh wow, just tried this out and it is very cool. 

Now that the Builder is so capable in generating experiments, the Coder view could be seen as pretty much a "pro" feature of PsychoPy (when it used to be the front door of the app for most people). But anyone who actually takes Python programming seriously will pretty quickly jump ship to a dedicated text editor or IDE, due to the Coder view's limitations. These suggested features really do make Coder more of a viable tool, and give it an arrangement that will be familiar to anyone who has used any of a number of IDEs, whether for Python, R, MATLAB, etc. Having a more usable editor like this would certainly improve the situation for teaching purposes, at the very least.

I did find that it is currently a bit unstable - just attempting to switch between open tabs left the Coder window unresponsive and needing to be closed and re-opened.

Also, clicking on the source tree to navigate a large file requires double-clicking on the name of a function or class definition - I wonder if it would be possible there with just a single-click, which might be what most people expect from other IDEs.

Great work.

**Comment by peircej** [comment]
Yes, these are great additions! Noting the stability aspect I suggest including them in the 2020.2.0 release. So I'll pull this and the plugins branch as soon as the 2020.1.1 release goes out (this week)

**Comment by mdcutone** [comment]
> I did find that it is currently a bit unstable - just attempting to switch between open tabs reliably left the Coder window unresponsive and needing to be closed and re-opened.
> 

It's very fast on my system and may laptop is pretty low-end. Try updating wxPython to the latest version, it seems to be an issue with drawing the tree rather than the parser. 

> Also, clicking on the source tree to navigate a large file requires double-clicking on the name of a function or class definition - I wonder if it would be possible to jump there with just a single-click, which might be what most people expect from experience with other IDEs.
> 

Good suggestion, that can be easily done.

**Comment by m-macaskill** [comment]
> EDIT: Try it again, there was a handled exception being triggered that might have been slowing things down too.

It now works perfectly for me, along with the single-click navigation. This is great stuff.

**Comment by mdcutone** [comment]
@m-macaskill @peircej Code auto completion and calltips are now working (you need 'jedi' installed to use them, logs error otherwise), also fixed loads of small bugs in coder. Try it out!

**Comment by mdcutone** [comment]
@peircej This is going to need a bit of work and testing before public release.

**Comment by peircej** [comment]
Yes. I'm now creating a separate branch for the current release series (2020.1.x) and those will stay as bug-fix commits only, but pulling your new features into master so that we can start testing them more widely (on the assumption that most devs work off master branch). I won't be releasing 2020.2 anytime soon, until we feel it's ready

**Pull request merged**
